server/package-lock.json
server/package.json
server/src/entity/meeting/meeting.entity.ts
server/src/meeting/meeting.module.ts
server/src/meeting/v0/dto/meeting-v0-create-meeting.dto.ts
server/src/meeting/v0/meeting-v0.service.ts
server/src/meeting/v1/dto/meeting-v1-create-meeting-body.dto.ts
server/src/meeting/v1/dto/meeting-v1-get-presigned-url-response.dto.ts
server/src/meeting/v1/dto/meeting-v1-update-meeting-body.dto.ts
server/src/meeting/v1/meeting-v1.controller.ts
server/src/meeting/v1/meeting-v1.module.ts
server/src/meeting/v1/meeting-v1.service.ts
server/src/shared/s3/dto/get-presigned-url/s3-get-presigned-url-response.dto.ts
server/src/shared/s3/dto/get-presigned-url/s3-get-presigned-url-response.fields.dto.ts
server/src/shared/s3/s3.module.ts
server/src/shared/s3/s3.repository.ts

- s3 presigned url을 파일사이즈를 제한하기 위해 POST로 구현
- s3 모듈은 다른 controller에서 사용할 수 있기에 shared디렉토리 하위에 구현
- 중복되는 구현이 v0에 있기 때문에 v1에 새로 구현

feat: s3-presigned url을 활용한 모임생성/수정 구현

---

server/src/auth/v0/auth-v0.controller.ts
server/src/auth/v0/auth-v0.service.ts
server/src/entity/user/user.entity.ts
server/src/internal-api/playground/dto/get-user-profile/playground-repository-get-user-profile.dto.ts
server/src/internal-api/playground/playground.repository.ts

#13
- playground authToken이 문제인 경우 401에러를 내보내도록 설정
- User스키마에 phone 필드를 nullable로 설정
- /auth 엔드포인트 호출시 자동으로 phone을 추가하도록 설정

[#13] feat: 유저 전화번호 추가

---

server/src/meeting/v0/meeting-v0.service.ts

[#16] feat: 2023.04.17.에 일정 기간동안 미팅 지원 불가능하도록 설정

---

server/src/entity/meeting/meeting.repository.ts

[#12] meeting 조회시 최근 만든 순으로 정렬되도록 변경

---

server/jest.config.ts
server/package-lock.json
server/package.json
server/src/entity/user/user.entity.ts
server/src/user/user.module.ts
server/src/user/v1/dto/user-v1-get-user-own-profile/user-v1-get-user-own-profile-response.dto.ts
server/src/user/v1/user-v1.controller.ts
server/src/user/v1/user-v1.module.ts
server/src/user/v1/user-v1.service.ts
server/test/unit/user/v1/user-service.test.ts

#24 
- profileImage에 null이 될 수 있는데 타입이 추가가 안되었던 경우 수정
- jest 설정 파일 외부로 새로 생성
- 테스트코드 작성
- 새로운 user엔드포인트 v1 생성

[#24] feat: 유저 정보 가져오는 API 구현

---

server/src/meeting/v1/meeting-v1.service.ts

#25 
- csv 파일 export 할 때 각오도 포함되도록 변경

[#25] csv 파일 export 시 각오도 포함되도록 변경

---

server/tsconfig.build.json

#30 
- config.ts 파일은 빌드시 포함 안되도록 변경
- test파일도 build시 export 제외

[#30] Build시 문제 수정

---

server/src/app.module.ts
server/src/entity/notice/notice.entity.ts
server/src/entity/notice/notice.repository.ts
server/src/notice/notice.module.ts
server/src/notice/v1/dto/notice-v1-create-notice-body.dto.ts
server/src/notice/v1/dto/notice-v1-get-notices-query.dto.ts
server/src/notice/v1/dto/notice-v1-get-notices-response.dto.ts
server/src/notice/v1/enum/get-notices-status.enum.ts
server/src/notice/v1/notice-v1.controller.ts
server/src/notice/v1/notice-v1.module.ts
server/src/notice/v1/notice-v1.service.ts
server/test/unit/notice/v1/notice-v1.service.test.ts

#34 
- 공지사항 조회/작성 기능 추가
- 테스트 코드 추가

[#34] 공지사항 기능 구현

---

README.md
server/src/common/constant/active-generation.const.ts

[#41] feat: 최신기수 33기로 변경

---

server/src/app.module.ts

#49
- force sync 옵션을 dev환경에서도 false로 작동하도록 변경

[#49] env: typeorm force sync 부분 변경

---

server/src/meeting/v0/meeting-v0.service.ts

- v0 모임 상세 조회 시, service단에서 invite 관련 레거시 걷어내는 작업 했습니다.
- 레거시 걷어내면서 approved 값이 제대로 계산 되지 않았던 오류를 수정하였습니다.
#53

[#53] 모임 상세 조회 시, approved 필드 값 구하는 로직 수정

---

server/src/user/v0/user-v0.service.ts

- 내 모임 페이지에서 신청한 모임 조회 시, 최신순으로 정렬해서 내려주도록 수정하였습니다.
- 지원한 모임의 데이터를 DB에서 꺼내올 때 DB에서 정렬을 할까 고민했는데, 추후 신청한 모임 내에서 정렬 기준이 추가 될 수도 있을 것 같아서 유연한 설계를 위해 서비스 로직에서 정렬하도록 했습니다. 
- closed #45

[#45] 신청한 모임 최신순으로 정렬

---

server/src/comment/v1/comment-v1.controller.ts
server/src/comment/v1/comment-v1.service.ts
server/src/comment/v1/dto/delete-comment/comment-v1-delete-comment-param.dto.ts
server/src/comment/v1/dto/update-comment/comment-v1-update-comment-body.dto.ts
server/src/comment/v1/dto/update-comment/comment-v1-update-comment-param.dto.ts
server/src/comment/v1/dto/update-comment/comment-v1-update-comment-response.dto.ts
server/src/post/v1/dto/delete-meeting-post/post-v1-delete-post-param.dto.ts
server/src/post/v1/dto/update-meeting-post/post-v1-update-post-body.dto.ts
server/src/post/v1/dto/update-meeting-post/post-v1-update-post-param.dto.ts
server/src/post/v1/dto/update-meeting-post/post-v1-update-post-response.dto.ts
server/src/post/v1/post-v1.controller.ts
server/src/post/v1/post-v1.service.ts

Close #56 
- 댓글/피드 삭제/수정 API 구현

[#56] 댓글/피드 삭제/수정 API 구현

---

server/src/post/v1/post-v1.service.ts

closed #67
- 사용하지 않는 콘솔로그를 삭제했습니다.

[#67] 사용하지 않는 콘솔로그를 삭제했습니다

---

server/src/entity/apply/apply.repository.ts
server/src/meeting/v0/meeting-v0.service.ts

closed #66 
- 쿼리로 받는 date 값에 따라 오래된순/최신순 정렬되도록 수정

[#66] 모임 지원자 리스트 조회 시, 오래된순/최신순 정렬되도록 수정

---

server/src/meeting/v0/meeting-v0.controller.ts
server/src/meeting/v1/meeting-v1.controller.ts
server/src/post/v1/post-v1.service.ts

closed #75
- 사용하지 않는 필드 및 transaction삭제

[#75] 모임 게시글 삭제시 해당 정보만 삭제하도록 변경

---

server/src/entity/meeting/meeting.repository.ts

closed #78 
- 내 모임 페이지 내, 내가 만든 모임 최신순으로 정렬하도록 구현했습니다.

[#78] 내가 만든 모임 최신순 정렬

---

server/package-lock.json
server/package.json
server/src/common/utils/swagger.ts

[#82] v0.5.3

---

main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
main/src/main/java/org/sopt/makers/crew/main/entity/report/Report.java
main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java

- report 부분의 package 구문에 잘못 설정 했던 부분을 수정
- 리뷰는 2023-12-02 옆자리에서 받았습니다~!
closed #88

[#88] env: [Spring] 패키지간 import 문제 해결

---

server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-query.dto.ts
server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
server/src/post/v1/post-v1.service.ts

- 전체 모임의 게시글을 조회하도록 변경 및 모임 정보도 함께 추가
- 해당 코드 다음 버전이 생기면 Spring에 작성하기
- closed #91

[#91] feat: [모임] 전체 모임의 게시글을 조회하도록 변경 및 모임 정보도 함께 추가

---

main/src/main/java/org/sopt/makers/crew/main/common/config/WebMvcConfig.java

- 스프링 서버에서 발생하는 CORS 에러 해결했습니다 !
- closed #99

[#99] fix: CORS 관련 config 추가

---

main/build.gradle
main/src/main/java/org/sopt/makers/crew/main/common/config/SwaggerConfig.java
server/package-lock.json
server/package.json
server/src/common/utils/swagger.ts

[#104] v1.0.0

---

main/src/main/resources/application-prod.yml

- Spring Prod 환경변수 추가
- 리뷰 하지 말아주세요
- closed #107

[#107] env: spring Prod 환경변수 추가

---

main/build.gradle
main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
main/src/main/java/org/sopt/makers/crew/main/common/config/SwaggerConfig.java
server/package-lock.json
server/package.json
server/src/common/utils/swagger.ts

- Swagger Spring Prod 환경 설정 && v1.0.2
- 절대 밤을 새지마
- closed #111
- closed #112

Swagger Spring Prod 환경 설정 && v1.0.2

---

server/src/common/constant/active-generation.const.ts

- 내일부터 시작될 34기를 위해 상수값 변경했습니다!
- closed #

[CHORE] 활동기수 변경

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

- 플그 마이페이지 내 모임 조회 API, 204 status code 시 성공 response body로 내려가도록 수정했습니다.
- 플그 FE 측에서 배포 일정에 맞도록 급하게 수정 요청이 들어와서 바로 머지한 점 양해 부탁드립니다 !
- closed #136

[FIX] 플그 마이페이지 내 모임 조회 API, 204 status code 시 성공 response body로 내려가도록 수정

---

docker-compose.yml

- Time Zone를 서울로 추가했습니다!
- closed #146

[FIX] 도커 컴포즈 TimeZone seoul 추가

---

package-lock.json
server/package-lock.json
server/package.json

[CHORE] nest.js 의존성 추가

---

docker-compose.yml
main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2CreateCommentBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2CreateCommentResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java
server/src/comment/v1/comment-v1.controller.ts

- "내가 작성한 모임에 댓글이 작성 되었을 때" 푸시 알림을 보내는 작업을 했습니다.
- 해당 작업을 하기 위해 모임 게시글 댓글 작성 API를 스프링으로 v1 -> v2로 마이그레이션 완료 했습니다.
- closed #118

[FEAT] 모임 게시글 댓글 작성 API 마이그레이션 및 알림 작업

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

- 모임 둘러보기 API 응답에 모집 시작시간(`startDate`) 추가
- 배포시 같이 나가면 될 것 같습니다!
- closed #153

[#153] feat: 모임 둘러보기 API 응답에 모임 모집시작시간 추가

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

- 모임 모집 시작 시간 대신 모임 모집 종료 시간이 내려가던 문제 수정
- 모임 모집 종료시간 추가로 응답 리턴
- nope
- closed #157

[#157] fix: 모임 홈 개선 - 모임 둘러보기 API 응답 모임 모집기간 수정

---

main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java

- 테스트 코드 제가 mocking을 잘못한 부분이 있었네여..ㅎㅎ 죄송합니당
- 해당 코드 수정 + application.properties 수정하니까 정상동작 확인했습니다!
- closed #159

[FIX] 테스트 코드 오류 수정

---

main/Dockerfile

-  Dockerfile 로 이미지 빌드할 때 테스트 코드 실행안하도록 수정했습니다!
-  스프링 컨테이너내에서 테스트 컨테이너를 사용하면 DinD(Docker in Docker) 구조가 된다고 하는데요! 
- 이 방식이 간단하지도 않을뿐더러, 보안상 권장하지도 않는다고 합니다!
- 그래서 도커파일로 빌드할 때 `-x test` 옵션을 붙여 Dockerfile로 빌드할 때는 테스트 코드가 실행되지 않도록 했습니다!
- 도커파일에 해당 옵션을 붙인 것은 "참고링크2" 글 보고 결정했습니다!
- 저희는 CI 과정있기에 이 옵션을 붙여도 괜찮겠다고 생각을 했습니다!
- 더 좋은 의견 있으시면 말씀주세요 :)
- 참고링크1 : https://github.com/testcontainers/testcontainers-java/issues/1112
- 참고링크2 : https://stackoverflow.com/questions/76245035/spring-boot-integration-test-failing-with-testcontainers-and-gradle-in-docker-co
- closed #163

[FIX] Dockerfile 로 이미지 빌드할 때 테스트 코드 실행안하도록 수정

---

docker-compose.yml

- /post/v2, /comment/v2 라우트 규칙 추가

[FIX] Route 규칙 변경

---

main/src/main/resources/application-prod.yml

- 로그에 sql를 제거했습니다. 
- 운영 환경에만 제거했고, 개발환경에는 나름 의미가 있을 것 같아서 그대로 뒀습니다!
- closed #177

[CHORE] 로그에 sql 제거

---

main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java

- 400번 에러 발생 시 내려드리는 메세지를 alert 창에 바로 사용함에 따라, 요청사항 대로 라이팅 수정했습니다.
- closed #183

[CHORE] 모임 지원/취소 API 에러 메세지 수정

---

main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java

- 스웨거 cors 이슈 해결했습니다.
- 경험상 이렇게 하면 되는 걸로 알고 있는데, 만약 문제 생기면 다시 알아보겠습니다..! (로컬에서 테스트 하기가 번거로워서..)
- closed #

[FIX] 스웨거 이슈 해결

---

docker-compose.yml

- 라우팅 규칙 변경한 뒤, 해당 파일을 복붙해서 ec2내에 저장했더니 cd 문제가 생겼습니다!
- 그래서 이와 관련해서 일부 수정이 있었습니다!
- closed #209

[FIX] 오류 수정

---

docker-compose.yml

[FIX] 라우팅 규칙 편집

---

main/src/main/java/org/sopt/makers/crew/main/notice/dto/response/NoticeV2GetResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/notice/service/NoticeV2Service.java

공지사항 조회 API id 데이터 추가
- FE 요청으로 해당 데이터값 추가합니다.
- closed #235

[CHORE] 공지사항 조회 API id 데이터 추가

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2ReportCommentResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
main/src/main/java/org/sopt/makers/crew/main/entity/report/Report.java
main/src/main/java/org/sopt/makers/crew/main/entity/report/ReportRepository.java
main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
server/src/comment/v1/comment-v1.controller.ts

- Spring 프로젝트에 댓글 신고하기 V2 API 구현
- 사용하지 않는 댓글 신고하기 V1 API에 deprecated 처리
- Spring에 잘못 매핑되어있던 신고 테이블 정보 수정
- 테스트코드는 나중에...
- closed #216

[FEAT] 댓글 신고하기 V2 API 구현

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java

- userId를 orgId로 수정했고, 다른 로직에서도 userId가 아닌 orgId가 필요한 부분이 있어 수정했습니다!
- closed #250

[FIX] userId -> orgId로 수정 및 orgId 필요한 로직에 데이터 추가

---

main/src/main/java/org/sopt/makers/crew/main/common/util/MentionSecretStringRemover.java

[HOTFIX] 비밀문자열 패턴 수정

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java

- 알림 메세지 변경했습니다.
- closed #256

[CHORE] 알림 메세지 변경

---

main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java

- 피드 작성 API 수정했습니다.
- 연관관계 제거 작업에서 제 휴먼에러가 있어서 바로 수정했습니다..!
- closed #261

[FIX] 피드 작성 API 수정

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java

- 멘션 알림 멘트를 실제 댓글 내용을 수정했습니다.
- closed #265

[FIX] 멘션 알림 멘트 변경

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java

- 멘션 내용에 큰 따옴표를 추가했습니다.
- closed #268

[CHORE] 큰 따옴표 추가

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/query/CommentV2GetCommentsQueryDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2CreateCommentBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2CreateCommentResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2ReportCommentResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2UpdateCommentResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplicantDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyInfoDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingGetApplyListResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2ApplyMeetingResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserMeetingDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseUserDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/query/PostGetPostsCommand.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2CreatePostResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostWriterInfoDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMeetingByUserMeetingDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java

- 이전에 모든 API에 대해서 스웨거 작성했습니다.
- closed #276

[DOCS] 스웨거 문서 작성

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java

- 스웨거 문서에서 requestBody로 오해할 수 있는 부분을 쿼리파람으로 변경했습니다
- closed #282

[fix] 스웨거 문서 수정

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java

-  좋아요 객체를 불러오는 곳에서 오류가 있었습니다.
- closed #284

fix: 좋아요 여부 로직 수정

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
server/src/notice/v1/notice-v1.controller.ts

- FE 요청사항에 따라 메타데이터를 추가했습니다.
- closed #289

[CHORE] 페이지네이션 메타데이터 추가

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java

- 댓글 삭제 후 조회 로직 오류를 해결했습니다.
- closed #291

[FIX] 댓글 삭제 후 조회 로직 오류 해결

---

main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java

- cors 에러로 인해 PUT 메서드를 추가했습니다.
- closed #293

fix: PUT 메서드 추가

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java

- 스웨거 설정에 오류가 있어 수정했습니다.
- closed #296

[fix] 스웨거 오류 해결

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java

fix: 스웨거 오류 해결

---

docker-compose.yml
main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementApi.java
main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementController.java
main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/Advertisement.java
main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementRepository.java

- 광고 조회 API 를 개발했습니다.
- closed #301

[FEAT] 광고 조회 API 개발

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2MentionUserInPostRequestDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java

- 댓글 업데이트 시점이 아닌 생성시점으로 변경했습니다.
- closed #303

[CHORE] 업데이트 -> 생성시점으로 변경

---

server/src/meeting/v0/meeting-v0.controller.ts

- 모임지원자 조회 API deprecated 처리
- closed #314

[CHORE] deprecated 처리

---

main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
server/src/meeting/v1/meeting-v1.controller.ts

- 모임 수정 API 마이그레이션 했습니다.
- 기존 메서드를 그대로 사용한 부분이 많습니다.
- closed #316

[FEAT] 모임 수정 API 마이그레이션

---

main/.gitignore
main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2UpdatePostBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2UpdatePostResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
main/src/test/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceTest.java
server/src/post/v1/post-v1.controller.ts

- 모임 게시글 수정 api 마이그레이션 했습니다.
- closed #295

[FEAT] 모임 게시글 수정 V2 API 구현

---

main/src/main/java/org/sopt/makers/crew/main/entity/apply/enums/EnApplyStatus.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingGetAppliesCsvQueryDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

- 신청 상태 컬럼 추가했습니다.
- 스웨거도 기존 형식과 동일하게 변경했습니다.
- closed #329

[CHORE] csv 파일 다운로드 로직 수정

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java

[DOCS] 스웨거 기존과 동일하게 수정

---

main/src/main/java/org/sopt/makers/crew/main/common/advice/ControllerExceptionAdvice.java
main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
main/src/main/java/org/sopt/makers/crew/main/common/exception/ExceptionResponse.java
main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationEntryPoint.java

- 예외 응답 개선했습니다.
- 이전에 예외가 발생했을 때, 관련 메세지가 없어 FE 쪽에서 디버깅의 어려움이 있었습니다.
- 그래서 저희가 예측 가능한 예외에 대해선 에러 메세지가 나가도록 설정했습니다.
- closed #334

refactor: 예외 응답 개선

---

main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetDto.java
main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementsGetResponseDto.java

- 변수명을 기능에 맞게 수정했습니다
- closed #339

chore: 변수명 수정

---

main/style-config/naver-checkstyle-rules.xml
main/style-config/naver-intellij-formatter.xml

- 코드리뷰를 효율적으로 하기 위해 인수인계 동안 코드 포맷터를 동일하게 합니다.
- closed #341

add: 코드 포맷터 추가

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2CreatePostBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2UpdatePostBodyDto.java

- 이미지 nullable 하게 수정
- closed #351

fix: 이미지 nullable 하게 수정

---

main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java

hotfix: 댓글 조회 수정

---

main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java

- 로직상 오류가 있었습니다 ㅎㅎㅎ..  테스트코드 도입이 시급하네요....ㅎㅎ... 수정했습니다!
- closed #373

fix: AppliedCount -> ApprovedCount 로 변경

---

main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java

- 기능에 맞게 desc 데이터 추가했습니다.
- closed #377

fix(Post): desc 데이터 추가

---

main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java

hotfix: 컬럼 이름 변경

---

main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java

hotfix: 컬럼 이름 변경 (#384)

---

main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java

hotfix: playground와 엔티티 싱크 맞추기

---

main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java

- 신청정보가 없는 경우에 대한 예외 처리 작업 진행했습니다.
- closed #389

fix: 모임 상세 조회 API 오류 수정

---

main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

-  신청 정보없는 경우에 대한 처리를 급하게 하느라 실수가 있었습니다,,,
- 이 부분은 테스트 코드 작성후에 마이그레이션 작업 진행하는게 좋을 것 같습니다.
- closed #393

fix: 신청 정보없는 경우에 대한 처리

---

main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
server/src/common/constant/active-generation.const.ts

- 현재 기수 35기로 수정했습니다.
- 상수클래스도 final 클래스로 만드는게 설계 측면에서 바람직하다고 생각해서 해당 PR에 넣어봤습니다..ㅎ
- closed #395 
- closed #348

chore: 현재 기수 35기로 수정

---

main/Dockerfile

- pinpoint를 적용했습니다.
- 현재는 일단 test 용도로 dev 서버를 모니터링 하고 있습니다. 추후에는 dev 서버 제외, prod 서버만 모니터링할 예정입니다.
- 일단 pinpoint 연결하는데 품을 너무 많이 써서 이 부분 일단 컨펌받고, 신고 기능 구현 완료 후에 다시 작업 진행해도 괜찮을까요??
위 로그와 같이 pinpoint 활성화 후에 저희가 알고 있는 spring 로그가 뜨면 pinpoint 정상 연결을 의미합니다.
</br>
url 링크 : https://www.notion.so/sopt-makers/cafbe8421e1144b9a4e63357d1ba75c5?pvs=4
위 사진과 같이 API 요청시간(각 요청마다도 트레이스가 가능합니다) 을 확인할 수 있으며, 프로메테우스처럼 기본적인 모니터링도 제공해줍니다!
자세한 기능은 아래 블로그를 참고해도 좋을 것 같아요!
https://jojoldu.tistory.com/573
- 현재 pinpoint 내의 `hbase` 사용함에 있어 이슈가 있습니다. 해당 이슈는 노션에 간단히 적어뒀습니다!
- https://www.notion.so/sopt-makers/e8cdd66c9b804516b088c3b0508e9ef0?pvs=4
- closed #369

refactor: pinpoint 적용

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
main/Dockerfile

- docker 파일 수정했습니다.
- closed #403

chore: docker 파일 수정

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
main/Dockerfile

feat: 모니터링 관련 사항 롤백

---

.github/workflows/cd-dev.yml

- cd에서 파일 실수로 적어서 수정했습니다.
- closed #407

fix: 모니터링 관련 수정

---

main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
main/src/main/resources/schema.sql
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/repository/MeetingRepositoryTest.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2MockServiceTest.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
main/src/test/resources/sql/apply-repository-test-data.sql
main/src/test/resources/sql/post-repository-test-data.sql

- 모임 생성, 수정 v2 API 유효성 검사 수정했습니다.
- `모임 생성` 에 대해 테스트코드도 작성했습니다.
- 현재 테스트 코드를 보시면, Mocking 된것과 실제 객체를 사용하는 케이스가 혼재되어 있습니다. 현재 제가 생각하는 방향은 Mocking은 외부 서비스에 한해서만 사용하고, 그 외에서는 실제 객체를 사용하는 방안을 생각하고 있습니다!
- mockist : 행위를 검증, 특정 행위를 했는지 검증
- 테스트 코드내에 구현이 드러나게 됨 → 테스트 코드에 대한 리팩토링 내성 약화 (자주 수정해야 됨)
- 특정 객체 내의 동작은 보장되지만 여러 객체간의 정상동작은 보장하지 못함
- 특정 결과값을 받을것이라고 가정한다는 것 자체가 위험, 완전성 보장 X
- classicist: 상태를 검증, 특정 행위후에 특정 객체의 상태를 검증
- 리팩토링 내성 강화
- 여러 객체간의 정상동작 보장
- 테스트 피드백 속도가 늦어짐
- 나만의 법칙 :
- 외부 서비스는 모킹을 한다.
- 상태 검증을 기본 원칙으로 하되, 테스트 피드백 속도가 느려짐이 관찰되면 mocking을 고민한다.
- 저도 잠깐 헷갈려서 다시 리마인드 드리면, 테스트 환경에서는 ddl-auto가 none으로 되어 있고, schema.sql로 테이블을 생성하고 있습니다. 따라서 앞으로 테이블이 변경되면 관련 테스트 코드가 성공하기 위해선 schema.sql 도 업데이트 되어야 합니다!!
- closed #411

chore: 모임 생성, 수정 v2 API 유효성 검사 수정

---

main/build.gradle
main/src/main/resources/application-test.yml
main/src/main/resources/logback-spring.xml

- 테스트 환경 개선했습니다.
- 테스트 환경에서도 로그가 뜨도록 수정했습니다.
- closed #422

chore: 테스트 환경 개선

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

- excel로 열었을 때, csv 한글 깨짐 이슈 해결
- 신청내역 사라짐에 따라 삭제
- closed #443

fix: excel로 열었을 때, csv 한글 깨짐 이슈 해결

---

main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java

chore: likeCount Notnull 추가

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java

- 공동 모임장 객체를 만들 때, 기존에 저장되어 있는 객체를 참조하지 않아 오류가 생겼습니다.
- 이를 방지해주는 테스트 코드도 작성했습니다.
- closed #469

fix: 모임 수정 오류 해결

---

main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java

fix: 메이커스 리드 임시조치

---

main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java

chore: 번개 -> 번쩍으로 변경

---

main/src/main/java/org/sopt/makers/crew/main/global/config/CrewDatabaseConfig.java
main/src/main/resources/application-local.yml

- LazyConnectionDataSourceProxy 를 적용했습니다.
- 관련해서 블로그로 정리했습니다. cc. https://gamxong.tistory.com/156#toc2 
- 실제 엄청난 성능개선을 하진 못했지만 다른 API 에선 성능 개선을 시도해볼만 한 것 같아 제안드려보고 싶습니다!
- closed #499

refactor: LazyConnectionDataSourceProxy 적용

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java

- isCoLeader 필드에 대한 getter를 추가했습니다. (이슈에 이유가 적혀있습니다!)
- local 서버 swagger에서 필드가 잡히는 것을 확인했습니다!
- closed #527

fix: 커스텀 getter 추가

---

main/src/main/resources/application-dev.yml

hotfix: 레디스 Host 수정

---

main/Dockerfile

-  pinpoint 의존성을 제거했습니다.
- 혹시몰라 주석처리했는데 의견있으시면 아예 지우도록 하겠습니다!
- closed #548

chore(Dockerfile): pinpoint 의존성 제거

---

main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java

1. 대상연도에 대한 queryParam 추가 : 플그쪽에서 요청사항에 따라 queryParam 추가 및, 쿼리 로직에 일부 수정이 있습니다.
2. N+1 문제 해결을 위한 fetchjoin 추가 : 로그를 보니 N+1 문제가 생겨서 이를 해결하기 위해 fetch join를 추가했습니다.
- closed #562

chore: 가장 빠르게 신청한 모임 수정

---

main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyWithoutWelcomeMessageDto.java
main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateAndUpdateResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateAndUpdateMeetingForFlashResponseDto.java

- 번쩍 모임 관련 로직에서 변경된 DTO 네이밍을 스키마 어노테이션에 미적용을 했던 문제가 있었습니다.
- 그래서 스키마 어노테이션에 변경된 DTO 네이밍을 적용시켰습니다.
- closed #566

chore: 변경된 DTO 네이밍 적용

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java

- 스웨거 내용이 누락돼서 추가했습니다.
- closed #

fix(Meeting): paginationType 스웨거 추가

---

main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingCountResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java

- 특정 기수 모임 개수 반환하는 로직을 구현했습니다.
- 해당 API는 공홈팀에서 사용하는 API 입니다!
- closed #578

feat: 특정 기수 모임 개수 반환 (for 공홈 BE)

---

main/Dockerfile
main/scripts/entrypoint.sh

- SpringBoot 애플리케이션을 Pinpoint APM Agent와 함께 실행시키는 스크립트(entrypoint.sh)를 구현했습니다.
- Dockerfile에서 entrypoint.sh를 실행할 수 있도록 변경했습니다.
- closed #598

feat: Crew 스프링 서버를 Pinpoint Agent와 함께 실행하는 기능 구현

---

main/scripts/entrypoint.sh

- Pinpoint Agent 버전을 다운그레이드를 진행했습니다.
- 다운그레이드 이유는 아래 링크 참고 부탁드립니다!
https://www.notion.so/sopt-makers/Pinpoint-1bb76042aac28084a24cd72aedacac30?pvs=4
- closed #600

refactor: Pinpoint Agent 버전 다운그레이드 완료

---

main/build.gradle
main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingReader.java
main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheInfo.java
main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheQueryService.java
main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CachesEndpointExtension.java
main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CaffeineConfig.java
main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisConfig.java
main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingCacheDto.java
main/src/main/resources/application-dev.yml
main/src/test/java/org/sopt/makers/crew/main/external/CaffeineCacheConfig.java
main/src/test/java/org/sopt/makers/crew/main/external/CaffeineTestConfig.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java

이전 배포 과정중 겪었던 redis health check 이슈를 해결해요.
[관련 노션 정리글](https://www.notion.so/sopt-makers/redis-health-check-trouble-1c476042aac280c79743e8604a5c2636?pvs=4)
- #596

fix: redis health check 로 인한 blue green 배포 문제 해결

---

main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-traffic.yml

traffic 설정파일을 진행했어요!
- closed #602

feat: application-traffic.yml 세팅 진행

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
.github/workflows/cd-traffic.yml

- traffic 브랜치 전용 CD 스크립트 작성을 완료했습니다.
- 효준님 application-traffic.yml 작업 완료되면 머지 후 해당 feature 브랜치에 병합해서 같이 머지하면 될 것 같습니다
**- application-secrets.properties 수정되면 꼭 github action 환경변수에 업로드 해주세요!!!**
- closed #603

feat: traffic 브랜치 전용 CD 스크립트 작성 완료

---

main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-traffic.yml

feat: prod에 local redis health check 무시하도록 변경

---

main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-test.yml
main/src/main/resources/application-traffic.yml

- 센트리 환경변수 수정 및 운영환경과 세팅을 통일했습니다.
- closed #609

fix: 센트리 환경변수 수정 및 운영환경과 세팅 통일

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
.github/workflows/cd-traffic.yml
main/scripts/entrypoint.sh
main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-traffic.yml
main/src/main/resources/logback-spring.xml

- traffic 환경 agent 설정 추가
- closed #

fix: traffic 환경 agent 설정 추가

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
.github/workflows/cd-traffic.yml
main/scripts/entrypoint.sh
main/src/main/java/org/sopt/makers/crew/main/global/config/CrewDatabaseConfig.java
main/src/main/java/org/sopt/makers/crew/main/global/config/PlaygroundDataSourceConfig.java
main/src/main/java/org/sopt/makers/crew/main/global/util/RealTime.java
main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-traffic.yml
main/src/main/resources/logback-spring.xml

- traffic profile 설정 추가
- closed #

fix: traffic profile 설정 추가

---

.github/workflows/cd-traffic.yml
main/scripts/entrypoint.sh
main/src/main/java/org/sopt/makers/crew/main/global/config/CrewDatabaseConfig.java
main/src/main/java/org/sopt/makers/crew/main/global/config/PlaygroundDataSourceConfig.java
main/src/main/java/org/sopt/makers/crew/main/global/util/RealTime.java
main/src/main/resources/application-traffic.yml
main/src/main/resources/logback-spring.xml

- thread name prefix 오타를 수정했습니다.
- closed #612

fix: thread name prefix 오타 수정

---

main/src/main/resources/application-test.yml

- test.yml에 caffeine cache 설정 추가
한 번 확인은 해야할 거 같아서요! 확인해주시면 머지할게요!(혹시나 모르니..!)
- closed #622

refactor: test.yml에 caffeine cache 설정 추가

---

main/src/main/java/org/sopt/makers/crew/main/entity/flash/Flash.java
main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2Service.java
main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingLeaderUserIdDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java

- 번쩍 상세 조회 전, meeting과 flash 테이블의 userId 정합성 검증 및 동기화 로직을 추가했습니다. (이슈에 이유가 상세히 적혀있습니다)
- closed #554

refactor: 번쩍 상세 조회 전, meeting과 flash 테이블의 userId 정합성 검증 및 동기화 로직 추가

---

main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java

- openFeign으로 플그 서버로 호출 시 401에러를 반환하는 이유를 파악하기 위해 로그인 API에 토큰 로깅을 추가했습니다.
- closed #628

chore: 로그인 API에 토큰 로깅 추가 완료

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

공동모임장인 경우 내 모임에 뜨지 않는 경우가 있어 수정 진행하였습니다.
[이슈 관련 스레드](https://sopt-makers.slack.com/archives/C042SGKBFK7/p1744604983621419)
- closed #632

fix: 공동모임장인 경우 내 모임에 뜨지 않는 사항 수정

---

.github/workflows/cd-traffic.yml
main/src/main/java/org/sopt/makers/crew/main/entity/apply/enums/EnApplyType.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java

- 신청 부하 테스트를 걸기 위한 비즈니스 로직 제작하였어요!
- url은 비~~밀 요소라 요청하는 부분만 녹화했어요!
https://github.com/user-attachments/assets/b85263c4-abcb-4556-b58a-d4294c661403
- 들었던 생각은 아니지만! 저희 traffic rds 자체가 터널링을 통해 접속할 수 있게 되어서 로컬에서 실행하기 위해 터널링을 진행했어야 했어요!
- 추가로 traffic 환경이 완벽하게 main과 sync되어있는 secret.properties가 아니었다보니 일부 sentry 환경 변수를 수정하는 과정이 있었어요!
- 이에 관하여 정리한 문서 첨부해요 해당 pr slack 코멘트에 적어놓을 게요!
- closed #653

feat: 모임 신청 부하 테스트를 위한 api 비즈니스 로직들 구현 진행

---

main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheQueryService.java
main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CachesEndpointExtension.java
main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-test.yml
main/src/main/resources/application-traffic.yml
main/src/test/java/org/sopt/makers/crew/main/external/CaffeineCacheTest.java

- cache clear 할 수 있도록 진행하였어요!
- 다음과 같이 사용할 수 있어요!
- actuator 주소/cachecontents : 모든 캐시 무효화
- actuator 주소/cachecontents/캐시이름: 해당 캐시 내용 안에 있는 것 무효화
- actuator 주소/cachecontents/캐시이름/키 : 해당 캐시의 키 내용 무효화
- closed #644

feat: cache clear 작업 진행

---

main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java

- eqJoinableParts 메서드의 로직을 수정하여 파트 필터링 방식을 변경했습니다.
- 기존 교집합(AND) 로직에서 합집합(OR) 로직으로 수정했습니다.
- 코드 가독성 개선을 위한 메서드 분리 및 스트림 API를 활용했습니다.
이 PR을 진행하면서 여러 구현 방식을 시도해보았습니다:
```java
String partsArray = Arrays.stream(joinableParts)
.map(part -> "\"" + part.name() + "\"")
.collect(Collectors.joining(", ", "array[", "]"));
return Expressions.booleanTemplate(
"{0}::text[] ?| " + partsArray,
meeting.joinableParts
);
```
- Hibernate/JPQL에서 PostgreSQL 배열 연산자를 지원하지 않아 에러 발생
```java
String condition = "(" + 
Arrays.stream(joinableParts)
.map(part -> "arraycontains({0}, ''{" + part.name() + "}'')")
.collect(Collectors.joining(" or ")) + 
")";
return Expressions.booleanTemplate(condition, meeting.joinableParts);
```
- 템플릿 문자열이 HQL 파싱 오류를 발생시킴
- 프로젝트 구조와 제약사항으로 인해 적용하기 어려움
```java
private BooleanExpression …
```

refactor: 필터링 교집합 조건 합집합 조건으로 변경 완료

---

main/build.gradle
main/src/main/java/org/sopt/makers/crew/main/admin/v2/AdminV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Api.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/HomePropertyResponse.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/PropertyResponse.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminFacade.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminKeyProvider.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminService.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/JsonPrettierService.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/JsonPrettierServiceImpl.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/dto/AdminPagePresenter.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/dto/HomeProperties.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/vo/MainPageContentVo.java
main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/vo/PropertyVo.java
main/src/main/java/org/sopt/makers/crew/main/entity/property/Property.java
main/src/main/java/org/sopt/makers/crew/main/entity/property/PropertyRepository.java
main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
main/src/main/resources/application-dev.yml
main/src/main/resources/application-prod.yml
main/src/main/resources/application-test.yml
main/src/main/resources/application-traffic.yml
main/src/main/resources/templates/propertyPage.html

- 크루의 기디, 웹분들이 필요하신 어드민 페이지를 만들었어요! editable 컨텐츠를 직접 fe에서 수정하지 않아도 반영할 수 있도록 변경하였어요!
https://github.com/user-attachments/assets/3f63f5ef-94b4-4a36-8279-a1681d2e329e
- 추가로 fe에서 모든 프로퍼티를 조회하고 사용할 수 있도록 아래와 같이 api를 하나 제작하였어요! 추후 요청이 들어오면 key 단건으로 조회할 수 있도록 만들어볼 생각이에요!
우선은 쏘선생님, 커서 선생님과 함께 ui는 만들었기에 몇몇 코드들은 어색한 코드들이 있을 수 있어요! 1차 배포 나간 이후 요청사항이 추가로 있을 것이라 생각하여서 리팩토링 계속 진행할게요!
- closed #657

feat: editable 컨텐츠를 위한 admin api 를 만들어요 (1차 배포)

---

main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/MeetingKeywordType.java
main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateAndUpdateMeetingBodyDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAppliedMeetingByUserResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetCreatedMeetingByUserResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
main/src/test/resources/sql/user-service-test-data.sql

- /meeting/v2, /user/v2/apply,/user/v2/meeting에 startDate, endDate도 response로 추가했습니다.
- 위에 언급한 API에 welcomeMessage, meetingKeyword를 추가했습니다.
- 위에 언급한 API에 appliedCount를 삭제했습니다.
- closed #661

refactor: 기획 정책 변경으로 인한 모임 키워드 로직 리팩토링 완료

---

main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostLikeRequestDto.java
main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostLikeResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java

- 게시글 좋아요 토글(추가/취소) 기능을 내부 internal API로 제작했습니다.
- closed #693

feat: 플그를 위한 좋아요 동기화 API 구현

---

main/src/main/java/org/sopt/makers/crew/main/internal/InternalPostApi.java
main/src/main/java/org/sopt/makers/crew/main/internal/InternalPostController.java
main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostCreateRequestDto.java
main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostCreateResponseDto.java
main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalPostService.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2CreatePostBodyDto.java

- 플그에서 모임 피드 작성 POST Internal API를 구현했습니다.
- closed #694

feat: 플그에서 모임 피드 작성 POST Internal API 구현

---

main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostResponseDto.java

기존 플그 피드에서 모임 피드 조회해오는 dto에 모임 페이지로 이동할 수 있도록 meetingId 추가하였습니다.
- closed #702

feat: meetingId 추가하여 dto 설정 진행

---

main/src/main/java/org/sopt/makers/crew/main/global/config/WebMvcConfig.java

allowCredential True로 변경하여 preFlight 실패하지 않도록 수정
- closed #

fix: allowCredential True로 변경하여 preFlight 실패하지 않도록 수정

---

main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java

- 모임 조회 및 지원자 조회 API의 queryCommand 파라미터를 Swagger 문서에서 hidden 처리를 진행했습니다.
- closed #709

chore: 모임 조회 및 지원자 조회 API의 queryCommand 파라미터를 Swagger 문서에서 hidden 처리

---

main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ConcurrencyTest.java

테스트 진행 시 다른 테스트에서의 영향을 더 받지 않도록 sleep기간 늘리는 작업 진행
- closed #

fix: 테스트 진행 시 다른 테스트에서의 영향을 더 받지 않도록 sleep기간 늘리는 작업 진행

---

.github/workflows/prod-ci-cd.yml
main/src/main/java/org/sopt/makers/crew/main/global/constant/CrewConst.java

- 최신기수를 관리하는 ACTIVE_GENERATION 상수값을 36에서 37로 변경
- closed #725

feat: 최신기수를 관리하는 ACTIVE_GENERATION 상수값을 36에서 37로 변경
