sopt-makers/sopt-crew-backend

- server/package-lock.json
- server/package.json
- server/src/entity/user/user.entity.ts
- server/src/meeting/v0/meeting-v0.service.ts
- server/src/user/v1/dto/user-v1-get-user-own-profile/user-v1-get-user-own-profile-response.dto.ts
- server/src/user/v1/user-v1.service.ts
- server/test/unit/meeting/v0/meeting-v0.service.test.ts
- server/test/unit/user/v1/user-v1.service.test.ts
#32 
- test 라이브러리 버전 불일치 문제 수정
- 변경 사항에 대해서만 테스트 코드 작성(TDD)
- 유저 정보 조회시 활동이 없을 경우 hasActivities를 플래그로 내려준다.
- 누락된 User 엔티티의 activities 타입에 null 추가
> [#32] 사용자의 활동이 비었을 때의 예외처리 추가

- server/src/entity/meeting/meeting.entity.ts
- server/src/entity/meeting/meeting.repository.ts
- server/src/meeting/v0/dto/get-all-meetings/meeting-v0-get-all-meetings-query.dto.ts
- server/src/meeting/v0/dto/meeting-v0-get-meeting-by-id-response.dto.ts
- server/src/meeting/v0/meeting-v0.service.ts
- server/src/meeting/v1/meeting-v1.service.ts
- meeting entity에 `createdGeneration`필드 추가
- v0 미팅 조회 API에 생성 기수를 기준으로 조회 가능하도록 수정
- v1 미팅 생성시 현재 기수를 기준으로 `createdGeneration`필드가 채워지도록 변경
#47
> [#47] feat: 미팅 조회시 생성 기수별로 가능하도록 수정

- server/src/comment/v1/comment-v1.controller.ts
- server/src/common/decorator/api-ok-response-common.decorator.ts
- server/src/common/dto/common-response.dto.ts
- server/src/common/interceptor/transform.interceptor.ts
- server/src/common/utils/swagger.ts
- server/src/meeting/v0/meeting-v0.controller.ts
- server/src/meeting/v1/meeting-v1.controller.ts
- server/src/notice/v1/notice-v1.controller.ts
- server/src/post/v1/post-v1.controller.ts
- server/src/user/v0/dto/get-apply-by-user/user-v0-get-apply-by-user-apply-meeting.dto.ts
- server/src/user/v0/dto/get-apply-by-user/user-v0-get-apply-by-user-apply.dto.ts
- server/src/user/v0/dto/get-apply-by-user/user-v0-get-apply-by-user.dto.ts
- server/src/user/v0/dto/get-meeting-by-user/user-v0-get-meeting-by-user-meeting.dto.ts
- server/src/user/v0/dto/get-meeting-by-user/user-v0-get-meeting-by-user.dto.ts
- server/src/user/v0/user-v0.controller.ts
- server/src/user/v0/user-v0.service.ts
- server/src/user/v1/user-v1.controller.ts
#43 
- 성공 응답모델 문서에 CommonResponseDto를 래핑해서 노출되도록 수정
- ApiOkResponseCommon 데코레이터를 이용해 문서에 적용
- 일부 응답 Dto가 없었던 API의 응답 Dto 정의
> [#43] docs: 성공 응답모델 문서에 CommonResponseDto 적용

- server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
- server/src/post/v1/post-v1.service.ts
- server/src/user/v0/user-v0.service.ts
- v1 모임 게시물 조회 API의 reponse에 meeting 데이터 추가
#51
> [#51] 모임 게시글 조회 시, 모임 데이터도 response에 추가

- server/src/comment/v1/comment-v1.controller.ts
- server/src/comment/v1/comment-v1.service.ts
- server/src/meeting/v0/meeting-v0.controller.ts
- server/src/meeting/v0/meeting-v0.service.ts
- server/src/meeting/v1/meeting-v1.controller.ts
- server/src/meeting/v1/meeting-v1.service.ts
- server/src/post/v1/post-v1.service.ts
- 조회 api의 response에서 null 대신 빈 배열로 처리하도록 수정하였습니다.
#57
> [#57] 조회 api의 response에서 null 대신 빈 배열로 처리

- server/src/comment/v1/comment-v1.service.ts
- server/src/comment/v1/dto/get-comments/comment-v1-get-comments-response.dto.ts
- server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
- server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
- server/src/post/v1/post-v1.service.ts
- post와 comment 조회 api의 response에서, 유저 orgId를 추가해서 내려주도록 수정했습니다.
closed #62
> [#62] 댓글 및 피드 조회 api의 response에 유저 orgId 추가

- server/src/post/v1/post-v1.service.ts
closed #64 
- 3개 제한이었던 프로필 사진 수를 제한 해제 시킴
> [#64] 피드 댓글 작성자 프로필 이미지 및 개수 전체 개수를 내려주도록 수정

- server/src/meeting/v1/meeting-v1.service.ts
closed #80 
- 모임 지원자 리스트를 Export 하는 csv 파일에 참여자의 파트 정보 컬럼을 추가합니다.
> 모임 지원자 Export 하는 csv 파일에 참여자의 파트 정보 컬럼 추가

- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMeetingByUserMeetingDto.java
- 내가 속한 모임 리스트 조회 API의 reponse에서 모임 이미지 필드명을 기존 api와 맞춰 imageUrl로 수정했습니다.
- closed #96
> [#96] fix: 모임 이미지 필드명 통일

- server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
- server/src/post/v1/post-v1.service.ts
-  GET /post/v1/{postID} 엔드포인트 응답 결과로 모임의 desc 필드를 추가해서 내려주도록 구현했습니다.
- 다른 meeting을 내려주는 response dto 를 확인해보니 모임 소개 필드를 desc로 내려주고 있어서 여기서도 필드명은 통일했습니다 !
- closed #95
> [#95] add : 모임의 정보중 모임 소개 데이터 필드 추가

- main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
- main/src/main/java/org/sopt/makers/crew/main/common/pagination/dto/PageMetaDto.java
- main/src/main/java/org/sopt/makers/crew/main/common/pagination/dto/PageOptionsDto.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingByOrgUserQueryDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserMeetingDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- pagination 관련 파일 추가해서 api 개발 진행했습니다.
- 플레이그라운드 마이페이지 내 모임 영역에 필요한 데이터 컬럼만 뽑아서 내려줄 수 있도록 구현했습니다.
-  id : 모임 id
-  isMeetingLeader : 해당 모임의 개설자인지
-  title : 모임 타이틀
-  imageUrl : 모임 썸네일 Url
-  category : 모임 카테고리
-  mStartDate : 모임 활동 시작 날짜
-  mEndDate : 모임 활동 종료 날짜
-  isActiveMeeting: 활동중인 모임인지 여부
- 영우님과 코드 포맷팅이 다르게 설정되어있었나봅니다 ㅠㅠ 어떤걸로 세팅해두셨는지 알려주시면 제가 바꿔볼게요..!
pagination 관해서 한 가지 의견을 여쭤보고 싶은게 있는데요...! 
지금 이 api의 서비스 로직의 경우, 내가 참여한 모임 리스트를 조회하다 보니 `내가 개설한 모임`과 `내가 지원하고 참여한 모임` 두 개를 합쳐서 내려줘야하는데요. 
apply 테이블과 조인을 해서 meeting 데이터를 가져온 것과 meeting 테이블에서 userId를 통해 가져온 데이터를 합쳐서 내려줄려면 DB 조회 쿼리 로직이 두 개로 나눠져야한다고 판단했습니다. 
그러다보니 DB 계층에서 페이지네이션이 되는게 아니라 서비스 계층에서 페이지네이션을 구현할 수 밖에 없다고 생각해서 일단 그렇게 구현해놓기는 했습니다.
혹시 제가 생각 못했던 방법이 있거나, 잘못 생각한 부분이 있는지 영우님 의견 들어보고 싶습니다 :)
- closed #122
> [#122] feat: 플레이그라운드 마이페이지 내 모임 영역 데이터 조회 api

- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/EnMeetingStatus.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/vo/ImageUrlVO.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
- main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationService.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseUserDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- 모임 둘러보기 API 개발
- Entity에서 `joinableParts` 필드 타입이 `MeetingJoinablePart[]`인데 converter를 이용해서 `List<MeetingJoinablePart>`로 변경할 수 있다면 좋겠습니다.
- endpoint 명을 `/meeting/v2/banner`로 정했는데 더 좋은 의견이 있으면 말씀해주시면 좋을 것 같습니다.
- 기존 meeting 조회 API와 같은 부분이 많다고 느껴지는데, 응답모델이 특이하게 banner에서만 사용하는 형식이라 다음과 같이 정했어요.
- VO에서 final 키워드를 삭제한 것은 다음과 같은 이유에서입니다.
> final field가 포함된 class 역시 JPA의 Entity가 될 수 없다.
>
> Entity class는 JPA에 의해 프록시 객체로 확장된다. 그리고 JPA는 이 프록시 객체를 생성할 때 Reflection API를 이용한다. reflection으로 객체를 생성하기 위해서는 그 객체가 기본 생성자를 가지고 있어야 한다. 이렇게 생성된 프록시 객체의 필드들을 초기화 하기 위해 setter를 사용한다. 하지만 final 필드는 setter를 이용해서 초기화할 수 없다. final 필드는 클래스 로딩 시점에 초기화 되거나 생성자를 이용해서만 초기화될 수 있다. 따라서 JPA의 Entity로 사용할 class는 final 필드를 가질 수 없다.
- 사용하지 않는 패키지를 import하는 것을 많이 봤는데, 해당 부분은 삭제하는 작업이 필요할 것 같습니다.
- vscode에서 구글 스타일 가이드를 적용해서 …
> [#125] feat: 모임 홈 개선 - 모임 둘러보기 API 개발

- main/src/main/java/org/sopt/makers/crew/main/common/exception/NoContentException.java
- main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- 플그 마이페이지 내 모임 조회 API에서 크루 DB에 등록되지 않은 orgUserId로 쿼리 넣어서 요청하면 401 에러가 발생했었습니다.
- 하지만 유저가 회원가입 직후라면 크루 DB에 등록되기 전인 것이 당연한 시나리오기 때문에, 401 에러가 아니라 204 No Content 에러를 던지도록 수정하였습니다. 
- closed #132
> [FIX] 플그 마이페이지 내 모임 조회 API, 401 에러 해결

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/MainApplication.java
- main/src/main/java/org/sopt/makers/crew/main/common/aop/ExecutionLoggingAop.java
- main/src/main/resources/console-appender.xml
- main/src/main/resources/logback-spring.xml
1. AOP 를 사용하여 인터셉터를 만들었습니다!
2. 로깅정보는 다음과 같습니다!
* 요청한 컨트롤러 메서드 종류
* 요청 파라미터, request body
* 요청한 userId
* API 실행시간
3. 로그 레벨은 5단계 중, INFO 이상으로 콘솔 출력만 하고 있습니다!
참고자료 : 
https://tecoble.techcourse.co.kr/post/2021-08-07-logback-tutorial
https://livenow14.tistory.com/64
https://jojoldu.tistory.com/773
- 컨테이너가 배포시 이전 컨테이너는 삭제되기 때문에 이전 로그파일을 볼 수 없다는 단점이 있습니다!
- 그래서 도커와 EC2간의 볼륨을 마운트하여 도커 로깅 파일을 영구적으로 저장 + 날짜 지나면 자동삭제로 구현하려고 했습니다
- 하지만 아직 인프라 작업중이기도 하고, 혹시나 1차 행사에 문제가 될까봐 조금은 방어적으로 구현했습니다..!
- closed #165
> [FEAT] 인터셉터 활용한 로깅 구현

- main/src/main/java/org/sopt/makers/crew/main/common/aop/ExecutionLoggingAop.java
- 저희 서비스는 모든 API 요청을 위해선 토큰이 필요한 줄 알았는데 그게 아니었습니다 !
- 플그에서 요청하는 "플레이그라운드 마이페이지 내 모임 정보 조회 API" 한에서는 플그에서 토큰없이 요청을 하고 있더라고요!
- 그래서 제가 며칠전에 구현한 로깅 인터셉터에서는 무조건 토큰을 가지고 요청하기에 `principle`이 항상 존재한다고 생각해서 구현을 했었는데요!
- 인터셉터에서 익명유저 요청(토큰없이 요청)로 요청할 경우 `userId` 를 가지고 올 수 없기 떄문에 에러가 발생하는 것을 확인했습니다!
- 그래서 해당 사항 수정해서 PR 올렸습니다!
- closed #171
> [FIX] 익명 유저 처리를 위한 수정

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
- main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/MeetingMapper.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- server/src/entity/meeting/enum/meeting-category.enum.ts
- 모임생성 API 마이그레이션 했습니다.
- dev db에도 저장해봤는데 "SP1 세미나 테스트"라는 모임을 만들어 봤습니다. (기존에 저장된 방식이랑 크게 다르지 않은지, 크게 문제가 없을지 더블체크 해주시면 감사할 것 같습니다..!)
- 최대한 기존 스펙에 어긋나지 않게 구현하려고 했고, 클라 입장에서 수정할게 없게끔 구현했습니다.
- SP1 관련해서 Enum에 세미나도 추가했습니다.
- 테스트 코드는 추가해서 다시 언급드리겠습니다.
- 시간 데이터 관련해서 `LocalDateTime`으로 되어있는데요! 기존 db에는 ms까지 적혀있어서 `ZonedDateTime`으로 해야할까 고민입니다! (종료 날짜를 자세히 보면 ms가 현재 구현된 방식으론 0으로 되어있는 반면, 기존 저장된 데이터는 ms가 999로 되어있습니다!)
- 기존 코드에서는 스웨거 관련된 코드가 비즈니스 로직과 혼재되어 있다는 생각이 들었습니다.
- 그래서 `MeetingApi` 인터페이스로 스웨거 관련된 내용을 따로 뺐고, 이를 컨트롤러에서 `implements` 했는데 의견 궁금합니다!
- 저는 개인적으로 Dto-엔티티 변환해줄 때 MapSturct를 선호해서 사용해봤습니다! 이에 대한 의견도 궁금합니다
- 참고링크 : https://medium.com/naver-cloud-platform/%EA%B8%B0%EC%88%A0-%EC%BB%A8%ED%85%90%EC%B8%A0-%EB%AC%B8%EC%9E%90-%EC%95%8C%EB%A6%BC-%EB%B0%9C%EC%86%A1-%EC%84%9C%EB%B9%84%EC%8A%A4-sens%EC …
> [FEAT] 모임생성 API 마이그레이션

- main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/common/util/UserPartUtil.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/ApplyMapper.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingCancelBodyDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2ApplyMeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- server/src/meeting/v0/meeting-v0.controller.ts
- server/src/meeting/v1/meeting-v1.controller.ts
- server/src/post/v1/post-v1.controller.ts
- 모임 지원/신청 API를 스프링 서버로 마이그레이션 했습니다.
- 마이그레이션 하면서 지원과 신청 API를 분리 하였습니다.
- 기존 Nest.js 에서 하드코딩 되어있던 행사 부분 레거시로 판단하고 제외하였습니다. 행사, 스터디 모두 개설할 때 모집 기간에 맞춰 validation 할 수 있도록 구현하였습니다.
- 모임 신청 같은 경우에는 중요한 로직이고, 발생되는 예외가 많다보니 해당 로직에 관한 테스트 코드까지 작성하여 검증하고자 하였으나, 시간 관계상 우선 스웨거로 각 케이스 테스트 해봤습니다. 
- 이상 없는 것 같아 작업한 내용 먼저 올려두고, 테스트 코드 지금 작성해보고 있는데 오늘 저녁~밤 이전까지 완료하여 다시 언급 드리도록 하겠습니다 !
- 조금 급하게 구현한 부분이 없지 않아서 이상한 부분이 있다면 바로 리뷰 남겨주세요 ! 빠르게 수정하도록 하겠습니다!
- closed #175
> [FEAT] 모임 지원 신청/취소 API 마이그레이션

- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- 클라선생님들의 요구사항에 따라 API request 방식을 변경했습니다. (request body -> path variable)
- meetingId를 쿼리 파라미터로 받을까 하다가, RESTful API의 원칙 중 하나인 URL이 리소스를 표현해야 한다는 원칙을 좀 더 지키고자 path variable로 받도록 하였습니다 !
- closed #181
> [FEAT] 모임 지원 취소 API 수정 

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- .github/workflows/ci.yml
- develop 브랜치에 merge시 ci, cd가 두번씩 실행되는 현상 확인
- develop, main 브랜치에 pr을 통해 merge 되면 CI를 수행 후 수행이 성공 했을 때만 CD를 수행하도록 개선
- 문제 발생 원인
- main, dev 브랜치 직접 푸쉬하는 경우도 있을 것 같아서 그것도 CI를 수행하도록 설정 해뒀는데, 이 경우 PR 날려서 Merge 하는 경우 CI가 두 번 수행되고 CI가 성공하면 CD 프로세스를 진행하도록 해둬서 CD도 두 번 수행됨
> Hotfix/cicd workflow 수정

- docker-compose.yml
- server/src/app.module.ts
- server/src/common/middleware/logger.middleware.ts
- server/src/main.ts
- Nest.js와 caddy의 액세스 로그를 남깁니다.
- 
- [캐디 공식문서 로그 format](https://caddyserver.com/docs/json/logging/)
- [캐디 공식문서 로그](https://caddyserver.com/docs/caddyfile/directives/log#multiple-outputs)
- [캐디 docker-proxy 문서](https://github.com/lucaslorentz/caddy-docker-proxy?tab=readme-ov-file#sites-snippets-and-global-options)
- [캐디 공식문서 캐디파일 format](https://caddyserver.com/docs/caddyfile/concepts)
- [express access log time diff 스택오버플로우](https://stackoverflow.com/questions/18538537/time-requests-in-nodejs-express)
- [NestJS 공식문서 log](https://docs.nestjs.com/techniques/logger)
- closed #26
> [CHORE] logger 개선

- server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
- server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
- server/src/post/v1/post-v1.service.ts
- 피드 목록과 상세 정보를 불러올 때 생성 시간이 아닌 수정 시간을 불러오는 문제 발견
- 스프링 코드 수정할 때는 테스트 코드로 검증해보겠습니다~
</br>
- closed https://github.com/sopt-makers/sopt-crew-backend/issues/199
> [FIX] 피드 작성 시간 표기 오류

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/common/config/JpaAuditingConfig.java
- main/src/main/java/org/sopt/makers/crew/main/common/util/UserUtil.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingGetApplyListCommand.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplicantDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyInfoDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingGetApplyListResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/resources/application-test.yml
- main/src/test/java/org/sopt/makers/crew/main/common/config/TestConfig.java
- main/src/test/java/org/sopt/makers/crew/main/entity/user/UserRepositoryTest.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/repository/ApplyRepositoryTest.java
- main/src/test/resources/sql/apply-repository-test-data.sql
- main/src/test/resources/sql/delete-all-data.sql
- 맥락 : `모임 신청자 리스트 조회 API` 에 기능적 이슈가 있었고, 해당 API에 대한 수정이 필요한 상황이었습니다. 이왕 수정해야하기 때문에 아예 spring으로 마이그레이션하면서 수정하는게 더 낫겠다고 판단해서 진행했습니다.
- 모임 신청자 리스트 조회 API 마이그레이션 했습니다.
- 스터디 개설자가 아닌 경우 `전하는 말`에 빈값이 들어가도록 구현했습니다.
- 이전 구현은 제가 이해하기론 먼저 메모리에 올린 후, 서비스 레이어에서 페이지네이션 작업을 해준 것으로 이해했습니다! 해당 방식은 쿼리가 1번 나간다는 장점이 있다고 생각이 들었지만, "서비스 레이어 코드의 복잡함 + 테이블 전체 데이터를 메모리에 올린다는 부담감"이 있다고 생각했습니다.
- 그래서 repository 단에서 querydsl과 offset를 활용해서 페이지네이션을 구현해봤습니다! 카운트 쿼리 1번이 추가됐지만 성능에 큰 차이를 주진 않을 것 같았습니다! 해당 제안에 대해 어떻게 생각하시는지 궁금합니다!
- 또한, Pageable 객체를 사용해봤습니다! 휴먼에러를 방지할 수 있는 것 같아서 저는 애용하는데요! 현재 ApplySearchRepositoryImpl 에서 파라미터로 받고 있습니다.
- @QueryProjection : 해당 어노테이션을 사용해서 querydsl를 사용했습니다. 엔티티와 다른 반환 타입인 경우 주로 Projections를 사용하는데요! 그 중 @QueryProjection 은 가장 안전한 바인딩 방법이라고 생각해서 자주 사용하는데 의견 궁금합니다!
- @QueryProjection 참고링크1 : …
> [FEAT] 모임 신청자 리스트 조회 API 마이그레이션

- docker-compose.yml
- main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
- server/src/entity/user/enum/user-part.enum.ts
- `메이커스 리드` -> `메이커스 팀장`으로 변경했습니다.
- db에도 `메이커스 팀장`으로 저장된 것 확인했습니다!
- 라우팅 규칙에서 빠트린 부분이 있어서 추가했습니다.
- 머지 전에 dev, prod ec2내에 반영후에 머지 하겠습니다!
- closed #196 
- closed #193
> [FIX] 메이커스 팀장 버그 & 라우팅 규칙 수정

- docker-compose.yml
- main/src/main/java/org/sopt/makers/crew/main/entity/notice/Notice.java
- main/src/main/java/org/sopt/makers/crew/main/entity/notice/NoticeRepository.java
- main/src/main/java/org/sopt/makers/crew/main/notice/NoticeV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/notice/NoticeV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/notice/dto/request/NoticeV2CreateRequestDto.java
- main/src/main/java/org/sopt/makers/crew/main/notice/dto/response/NoticeV2GetResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/notice/service/NoticeV2Service.java
- main/src/main/resources/application-dev.yml
- main/src/main/resources/application-prod.yml
- main/src/main/resources/application-test.yml
- 볼륨이 작아서 공지사항 작성과 조회 API를 모두 작업했습니다.
- 공지사항 관련해서 누구나 공지사항을 작성할 수 있는 것 같아서 API 요청시 시크릿값을 넣어야 하는 것으로 변경했습니다.
- 해당 파일(`application-secret.properties`) 내용은 인수인계 톡방에 공유드리겠습니다! CI 실패하는 이유는 이것 때문입니다!
- 이것과 관련해서 다른 의견 있으시면 편하게 말씀주세요!!
- closed #221
> [FEAT] 공지사항 관련 API 마이그레이션

- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/query/PostGetPostsCommand.java
- Open API Spec에 맞춰서 게시글 목록 조회 API 파라미터 구조를 수정했습니다.
- closed #231
> [FIX] Open API Spec에 맞춰서 게시글 목록 조회 API 파라미터 구조 수정

- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
- Open API Spec에 맞춰서 쿼리 파라미터 타입을 string -> integer로 지정해줬습니다.
- closed #233
> [FIX] Open API Spec에 맞춰서 쿼리 파라미터 타입 지정

- docker-compose.yml
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
- server/src/comment/v1/comment-v1.controller.ts
- Spring 프로젝트에 댓글 삭제 V2 API 구현
- 사용하지 않는 댓글 삭제 V1 API에 deprecated 처리
- 없습니다!
- closed #215
> [FEAT] 댓글 삭제 V2 API 구현

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/common/util/MentionSecretStringRemover.java
- 내가 쓴 글에 댓글이 달렸다는 알림을 보낼 때 비밀문자열 제거
- #249
> [FIX] 댓글 작성 알림 시 비밀문자열 제거

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/common/util/MentionSecretStringRemover.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comments.java
- 댓글 삭제 기능 수정 : 대댓글에 댓글을 단 유저의 멘션이 있으면 멘션내용을 `@_` 로 변경하는 로직을 추가했습니다. 이에 대한 맥락은 아래 있습니다!
- https://sopt-makers.slack.com/archives/C042SGKBFK7/p1721656913922079
- 댓글 수정 로직 일부 수정 : updateDate는 알아서 업데이트가 되기에 제거했습니다.
- closed #259
> [CHORE] 댓글 삭제 기능 수정 및 댓글 수정 로직 일부 수정

- main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostCountResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/post/v2/repository/PostRepositoryTest.java
- server/src/post/v1/post-v1.controller.ts
- 모임 게시글 단건 조회 및 모임 게시글 개수 조회 하는 API를 마이그레이션 했습니다.
- 기존에 모임 게시글 목록 조회 API의 response DTO에서 사용하고 있던 `PostDetailBaseDto` 를 최대한 재사용하고자 했습니다.
- 재사용할 때 meeting 정보 안에 imageURL 리스트가 있고 없고만 차이가 있었기 때문에, 기존 모임 게시글 목록 조회 API의 구조에서 imageURL 컬럼이 추가되는게 괜찮은지 FE 분들과 논의 진행했구요. 논의 스레드는 아래와 같습니다 !
- https://sopt-makers.slack.com/archives/C042SGKBFK7/p1719670283072089
- 따라서 모임 게시글 단건 조회 시에는 기존 모임 게시글 목록 조회 로직과 동일하므로 따로 테스트 코드를 작성하지는 않았습니다.
- closed #230
> [FEAT] 모임 게시글 단일 조회 및 모임 게시글 개수 조회 V2 API 구현

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- 스웨거 설정을 위해 ReplyDto를 생성했습니다.
- 뿐만 아니라, 댓글과 대댓글을 Dto 상으로 분리하는게 나중에 변화에도 유연하게 대처가 가능할 것 같아서 이렇게 수정했습니다!
- closed #280
> fix: ReplyDto 구현

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/common/dto/TempResponseDto.java
- 마이그레이션을 위한 임시 API 개발
- closed #286
> feat: 임시 API 개발

- main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- server/src/post/v1/post-v1.controller.ts
- 모임 게시글을 삭제하는 API를 V2로 마이그레이션 하였습니다.
- 개발 하다보니 이전에 모임 게시글 단건 조회에서 없는 게시글 id를 보냈을 때 예외 처리가 누락되어 있어서 해당 부분도 수정해놓았습니다.
- closed #278
> [FEAT] 모임 게시글 삭제 V2 API 구현

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2SwitchCommentLikeResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
- main/src/main/java/org/sopt/makers/crew/main/entity/like/Like.java
- main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
- server/src/comment/v1/comment-v1.controller.ts
- 기존 nestjs에 구현되어있던 게시글 댓글 좋아요 토글 V1 API를 Spring 에 구현했습니다.
본래 3기 마지막 알림 기능이 추가가 될 때 좋아요 누를 시에 알림이 가도록 설정해서 마이그레이션 시에 해당 기능을 붙이기로 했었습니다. 다만 고려할 점이 있어서 해당 기능을 붙이지 않았습니다.
- 사용자 실수로 좋아요를 더블클릭하는 경우 알림이 2번 갈 수 있습니다.
- 위의 문제를 해결하기 위해서는 별도의 배치 프로그램 (lambda 혹은 redis 활용)을 개발해서 주기적으로 좋아요 summary를 보내주는 방법이 있지만, 마이그레이션 시에는 기능 변경을 최소화 해야하므로 해당 기능은 구현하지 않았습니다.
- 추후 개선 사항있을 시에 아키텍처 개선 진행하면 좋을 것 같습니다.
- closed #217
> [FEAT] 게시글 댓글 좋아요 토글 V2 API 구현

- main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingCreatorDto.java
- main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
- server/src/meeting/v0/meeting-v0.controller.ts
- 전체모임 검색 및 필터링 마이그레이션
- 동적쿼리 및 페이지네이션을 type-safe하게 + 깔끔하게 처리하기 위해서 querydsl를 사용했습니다.
- querydsl에서 postgresql 문법인 @> 사용에서 어려움이 있었습니다.
- 해당 코드는 `eqJoinableParts` 이며, `booleanTemplate` 로 `arraycontains` 를 사용하여 구현했습니다.
- 단 3번의 쿼리로 적은 쿼리 수로 구현했습니다!
```
Hibernate: select m1_0."id",m1_0."canJoinOnlyActiveGeneration",m1_0."capacity",m1_0."category",m1_0."createdGeneration",m1_0."desc",m1_0."endDate",m1_0."imageURL",m1_0."isMentorNeeded",m1_0."joinableParts",m1_0."leaderDesc",m1_0."mEndDate",m1_0."mStartDate",m1_0."note",m1_0."processDesc",m1_0."startDate",m1_0."targetActiveGeneration",m1_0."targetDesc",m1_0."title",m1_0."userId",u1_0."id",u1_0."activities",u1_0."name",u1_0."orgId",u1_0."phone",u1_0."profileImage" from "meeting" m1_0 join "user" u1_0 on u1_0."id"=m1_0."userId" where …
```
> feat: 전체모임 검색 및 필터링 마이그레이션

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/common/advice/ControllerExceptionAdvice.java
- main/src/main/java/org/sopt/makers/crew/main/common/exception/CommonResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationFilter.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
- main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
- main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationService.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/notice/service/NoticeV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- server/src/meeting/v0/meeting-v0.controller.ts
- 모임 삭제 API 구현
- 삭제할 떄, 최소한의 쿼리를 사용해서 삭제하도록 구현했습니다.
- closed #312
> [FEAT] 모임 삭제 API 구현

- main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementImageDto.java
- main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
- main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementImage.java
- main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementImageRepository.java
- 광고 조회 할 때, 단건 -> 리스트로 수정됨에 따라 변경했습니다.
- closed #322
> [CHORE] 광고 조회 API 수정

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/external/s3/config/AwsProperties.java
- main/src/main/java/org/sopt/makers/crew/main/external/s3/config/AwsPropertiesConfiguration.java
- main/src/main/java/org/sopt/makers/crew/main/external/s3/config/S3Config.java
- main/src/main/java/org/sopt/makers/crew/main/external/s3/service/S3Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/AppliesCsvFileUrlResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlFieldResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlResponseDto.java
- main/src/main/resources/application-dev.yml
- main/src/main/resources/application-prod.yml
- main/src/main/resources/application-test.yml
- server/src/meeting/v1/meeting-v1.controller.ts
- presignedUrl 생성 로직을 구현했습니다.
- 제가 다른 프로젝트 하면서 항상 `PUT` 방식으로 했었는데요! 저희 프로젝트에서는 `POST` 를 사용하고 있었습니다!
- **이 부분이 나름 챌린징이었는데요! `java sdk` 에서는 `POST` 방식을 지원하고 있지 않았습니다...!**
- 처음에는 FE 분들에게 `PUT` 으로 변경하자고 요청드릴려고 했지만, 현재 마이그레이션이 밀려있는 상황에서 수정 요청을 드리는 건 큰 부담이라고 생각했습니다!
- 그래서 `POST` 를 통한 방식을 알아보고, 일일히 코드를 짜서 기존 API와 완전히 동일하게 구현했습니다!
- 이로 인해, 코드가 조금 복잡하지만 프론트에서 호출하는 것과 동일하게 호출해하여 잘 되는 것 확인했습니다!
- #321
> [FEAT] presignedUrl 생성 로직 구현

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
- main/src/main/java/org/sopt/makers/crew/main/external/s3/config/AwsProperties.java
- main/src/main/java/org/sopt/makers/crew/main/external/s3/service/S3Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/AppliesCsvFileUrlResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlFieldResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/resources/application-dev.yml
- main/src/main/resources/application-prod.yml
- main/src/main/resources/application-test.yml
- server/src/meeting/v1/meeting-v1.controller.ts
- csv 파일 업로드 및 url 반환 로직 구현했습니다.
- 전화번호 부분에서 예전 기능부터 앞에 "0"이 짤리는 문제가 있었습니다. 그래서 큰따옴표로 처리하여 선행 제로 문제를 해결했습니다.
- closed #321
> [FEAT] csv 파일 업로드 및 url 반환 로직 구현

- main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
- main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingCreatorDto.java
- main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplicantByMeetingDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyWholeInfoDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/entity/apply/AppliesTest.java
- main/src/test/java/org/sopt/makers/crew/main/entity/meeting/MeetingTest.java
- server/src/meeting/v0/meeting-v0.controller.ts
- 모임 상세 조회 API를 마이그레이션 했습니다.
- `List<Apply>` 부분을 `Applies` 라는 일급컬렉션을 만들어 관련 로직을 해당 클래스 내에 넣었습니다. 개인적으로 이런식으로 하는게 객체지향적이다 싶어서 추가해봤는데요! 변수명부터 시작해서 더 좋은 의견있으시면 말씀주세요!
- 참고링크 : https://jojoldu.tistory.com/412
- `now()` 라는 값이 Testability 를 많이 낮춘다고 생각했습니다!
- 그래서 의존성 주입으로 풀어내봤습니다. 테스트 코드 작성시에는 `MockTime` 클래스를 만들어서 테스트 코드를 작성했습니다!
- 참고링크 : https://jojoldu.tistory.com/676?category=1036934
- 현재 FE 의 마이그레이션 부담이 크기 때문에 이전 응답값과 동일하게 유지하기로 했습니다!
* **논의하게된 계기**
- 서비스 레이어쪽 테스트코드를 작성하려고 했었는데 알 수 없는 쿼리가 계속 발생하고, 이로 인해 테스트가 자꾸 실패했습니다..! 
- 조회임에도 불구하고 계속 user쪽에서 update문이 발생하고, 이로 인해 충돌이 발생하더라고요..
- 원인찾는게 어려울것 같아서 일단 제외하고 PR 올렸는데요! 개인적인 생각으론 양방향 매핑이 문제라는 생각이 들더라고요..!
* 제안
- 그래서 앞으로 연관관계 사용을 지양하고, 제가 필요하지 않는 연관관계 끊는 작업을 해도 괜찮을지 여쭤보고 싶었습니다!
- 예를 들어, `User` 엔티티의 `@OneToMany` 는 모두 다 필요하지 않다고 생각했습니다!
- 사실 테스트 코드를 …
> [FEAT] 모임 상세 조회 API 마이그레이션

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/entity/like/Like.java
- main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/main/java/org/sopt/makers/crew/main/entity/report/Report.java
- main/src/main/java/org/sopt/makers/crew/main/entity/report/ReportRepository.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2ReportResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2SwitchPostLikeResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
- main/src/test/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceTest.java
- server/src/post/v1/post-v1.controller.ts
- 게시글 좋아요 토글 및 게시글 신고 API V2를 구현했습니다.
- Like에 묶여있던 ManyToOne 연관 관계를 최대한 제거해서 예상치 못한 쿼리 발생을 줄이고자 했습니다.
- 그 과정에서 댓글 좋아요 토글 api 관련 코드에 약간씩 수정이 있었습니다.
- closed #328
> [FEAT] 게시글 좋아요 토글 및 게시글 신고 API V2 구현

- main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseUserDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- 기존 모임 배너 조회 로직을 개선했습니다.
- 부하상황 기준, API 평균 응답시간을 8초 -> 1초로 개선시켰습니다.
- 부하는 두 테스트 모두 동일한 환경에서 진행하였고, 100개의 스레드가 동시에 1초마다 요청하여 총 1분동안 테스트 진행하였습니다.
- closed #346
> refactor: 모임 배너 조회 로직 개선

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
- FE쪽에서의 마이그레이션 편의성을 위해 임시 API를 추가했습니다
- #333
> chore: 유저관련 temp API 추가

- main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/ApplyV2GetAppliedMeetingByUserResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
</br>
* 기존에 스웨거 상에서 mstartDate 로 보이는 문제가 있었습니다. 실제 응답에서는 그렇게 응답이 되지 않지만 스웨거 상에서만 보이는 것이었는데요! 프론트측에서 스웨거에 의존해 타입이나 변수명 같은 것을 정하고 있어서 올바르게 수정했습니다.
</br>
* 현재는 number 타입으로 되어있었는데 프론트측에서 Enum 으로 요청주셔서 수정했습니다!
* 이건 따로 이슈파서 하는게 맞지만 수정 범위가 작아서 같이 올려봅니다...!
* `NotNull`이 아닌데 제가 `NotNull` 로 validation 을 걸어놔서 수정했습니다...!
- closed #360
> chore: 모임 관련 API 스웨거에 보이는 응답값 수정

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
- main/src/main/resources/application-dev.yml
- main/src/main/resources/application-prod.yml
- main/src/main/resources/application-test.yml
- 모니터링 서버를 구축했습니다.
- 일단 세팅만 해뒀고, 세부적인 내용은 해보면서 알아가봐야 할 것 같습니다!
- AWS 계정은 `1. 온보딩 인수인계` 에 저장해뒀습니다!
- k6(부하테스트 툴)도 붙여볼 예정입니다
- 다른 의견 or 다른 툴 사용 생각하고 계시면 편하게 말씀주세요~~~!!
- 액츄에이터 사용은 안전하게 사용하면 좋을 것 같다는 생각을 했습니다! 그래서 디폴트는 모두 `disable` 시키고, 필요한 것들만 `enable` 시켰습니다! 
- 참고자료 (https://techblog.woowahan.com/9232/)
- closed #356
> feat: 모니터링 서버 구축

- main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetDto.java
- 요청에 따라 데이터를 추가했습니다.
- 맥락 : https://sopt-makers.slack.com/archives/C042SGKBFK7/p1725886816982949
- closed #364
> chore: 광고 조회 API 데이터 추가

- main/src/main/resources/application-local.yml
- 기존에 local.yml이 구축되어 있지 않았기에 로컬 작업을 위한 application-local.yml을 구현했습니다.
- 현재 postgreSQL에서 Enum 배열 타입을 JPA와 Hibernate를 통해 매핑할 때, `ddl-auto: create` 설정을 사용할 경우 Enum 배열 타입을 제대로 인식하지 못하는 문제가 발생합니다.
- 이에 대한 해결방법은 노션으로 남겨놓았으니 확인부탁드릴게요!
https://www.notion.so/sopt-makers/JPA-6b53bcdd07cb4675b689a89c1c40567a?pvs=4
- 추가로 `application-secret-properties`에 변경내용 반영해 놓았습니다!
- closed #372
> feat: application-local.yml 구현

- main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
- main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
- main/src/main/java/org/sopt/makers/crew/main/external/playground/TestService.java
- main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java
- main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlockRepository.java
- main/src/main/resources/application-dev.yml
- main/src/main/resources/application-local.yml
- main/src/main/resources/application-prod.yml
- 플그 db 연결 작업을 진행했습니다.
- read-only 계정을 만들어 일단 `플그 dev 테이블`만 or `플그 prod 테이블`만 조회 가능하도록 했습니다.
- 로컬의 경우, 현재 로컬 db에 플그 테이블이 추가되도록 생각했는데 의견 궁금합니다!
- 플그의 `member_block`은 연결시켜놨습니다! 간략하게 `TestService` 파일에 테스트 가능한 코드도 적었는데 이는 기능 구현할 때 삭제하면 좋을 것 같습니다!
- secret 값 변경은 노션에 업데이트했습니다!
- 문제 없이 잘 동작하는 거 확인하고, 플그에 있는 테이블에 접근해서 조회하는데도 성공했습니다!
- 하지만 아직 초기이고, 혹시 모르니 작업 전에 db를 pg_dump 로 db 백업 만드는 작업이 선행되면 좋을 것 같습니다! (약 3분이면 백업가능, 익숙치 않으시면 바로 말씀주세요!!)
- closed #371
> chore: 플그 db 연결 작업

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- 저번에 얘기한 도커헙에 태그 명시해주는 거 작업해봤습니다!
- 제가 잘못 알고 있는 부분 있다면 편하게 말씀주세요!!
- closed #368
> refactor: docker hub 푸시할 때 태그 추가

- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
- 스웨거 명세에 boolean variable에 붙은 is prefix를 인식 못하는 문제를 해결했습니다.
- boolean을 wrapper 타입인 Boolean으로 바꾸어줘서 is prefix를 인식을 하는 방법과, isBlockedPost를 Lombok getter에서 생략 후 직접 구현하는 방법이 있었습니다.
- 후자로 선택하게된 이유는 기존 boolean으로 필드를 구축했던건 null값을 허용하지 않으려는 의도였기 때문에, 명세를 위해 Boolean으로 바꾸는 것보다는 getter를 직접 구현하는게 더 의도에 맞다고 판단하였기 때문입니다.
- closed #396
> fix: isBlockedPost를 Lombok getter에서 생략 후 직접 getter 구현

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
- main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
- isBlockedComment를 Lombok getter에서 생략 후 직접 getter 구현하도록 변경했습니다.
- 스웨거 명세에도 잘 적용이 된 것을 확인했습니다.
- closed #399
> refactor: isBlockedComment를 Lombok getter에서 생략 후 직접 getter 구현 

- main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementsGetResponseDto.java
- FE 측에서 isSponsoredContent 필드를 추가함으로서 불필요한 리소스가 들게 되기 때문에, 삭제해달라는 요청을 받아 해당 필드를 삭제했습니다.
- 필드를 삭제한 후 광고 구좌 조회 시 isSponsoredContent 필드가 포함되지 않고 잘 작동하는 것을 확인했습니다.
- closed #418
> refactor: 광고 구좌 조회 응답 DTO에서 isSponsoredContent 필드 제거

- server/src/auth/v0/auth-v0.service.ts
```javascript
const { id, name, profileImage } = await this.playgroundService.getUser(
authToken,
);
const user = await this.userRepository.getUserByOrgId(id);
const userId: number = await (async () => {
if (!user) {
const newUser = await this.userRepository.save({
orgId: id,
name,
profileImage,
});
return newUser.id;
}
return user.id;
})();
```
```javascript
const playgroundUserActivities = await this.playgroundService.getUserActivities(
authToken, user.orgId
);
```
- 기존 코드는 user객체가 DB에 있는 지 조회 후 새롭게 newUser를 생성해 DB에 해당 정보를 저장하고 있었습니다.
- **문제가 되었던 부분은 user가 없을 때 새로운 유저(newUser)를 생성하고, 그 결과를 user 변수에 다시 할당하지 않았던 점입니다.** (회원가입 시 생성된 newUser를 user변수에 할당한 후 orgId에 접근해야 했지만, **할당하지 않고 원래 null이 였던 user 변수에 접근함으로서 TypeError가 발생!**)
- 에러 이후 두번째 요청때는 성공했었는데, 그 이유는 첫번재 호출 시점에서 이미 유저 정보가 DB에 저장된 …
> fix: 회원가입 시 user 객체를 생성한 후 orgId에 접근할 수 있도록 수정

- main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
- main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/resources/schema.sql
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- main/src/test/resources/sql/meeting-service-test-data.sql
- 모임 전체 조회 로직 수정
- 모임 전체 조회 테스트 일부 작성
- 원래는 모든 테스트 케이스를 고려해서 작성하려고 했었는데 데이터가 너무 많아 생각보다 시간이 오래걸리더라고요!
- 일단 1개 케이스가 PR 올렸고, 이 테스트를 성공시키기 위해 비즈니스 로직도 일부 수정했습니다.
- closed #431
> fix: 모임 전체 조회 로직 수정 & 모임 전체 조회 테스트 일부 작성

- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
- 모임 상세 조회 API 스웨거상 표기 오류가 있었습니다.
- closed #435
> fix: 모임상세조회 스웨거 명시 오류 해결

- main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- 조회수 증가 로직 오류 해결했습니다.
- 기존에 마이그레이션하다 해당 로직이 누락된 것 같습니다!
- 더 좋은 방법이 있다면 편하게 말씀주세요 !!
- closed #453
> fix: 조회수 증가 로직 오류 해결

- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllUserDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
- `전체 사용자 조회 API` 구현했습니다.
- 해당 기능은 모임 생성할 때, 멘션할 사용자 검색할 때 쓰이는 API 입니다.
- 기존에 FE 에서 사용했던 `멘션 사용자 조회 API` 를 `전체 사용자 조회 API` 로 마이그레이션 요청 드렸습니다!
- closed #
> feat: 전체 사용자 조회 API 구현

- main/src/main/java/org/sopt/makers/crew/main/global/aop/ExecutionLoggingAop.java
- 로그 출력용 AOP 구현했습니다.
- 현재 버전은 실행되는 모든 메서드의 시작과 끝을 로깅하고 있습니다.
- 로깅에 필요없거나 추가/수정 원하시는 부분있으면 편하게 말씀주세요!
- 처음에는 Aspect 를 사용해서 구현하려고 했습니다.
- 하지만 메서드마다 어노테이션을 붙이는건 너무 번거롭다고 생각했습니다.
- 그래서 클래스마다 어노테이션을 붙이는 방식으로 변경해봤습니다.
- 하지만 클래스마다 어노테이션 붙이는 방식마저도 너무 번거롭다고 생각했습니다.
- 그래서 전역적으로 실행시키는 방식으로 변경하고자 했습니다.
- 그러다보니 결국 제가 예전에 구현했던 `ExecutionLoggingAop` 의 형태로 하는게 맞는거 같더라고요!
- 그래서 현재 구현형태가 되었습니다!
- 추가로 테스트 코드 돌릴때는 해당 AOP가 동작하지 않도록 설정했습니다. 이거에 대해서도 의견궁금합니다! 저는 단순히 굳이 필요하지 않은 것 같아서 그랬습니다!
- closed #429
> feat: 로그 출력용 AOP 구현

- main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- 예전에 말씀드린 작업진행했습니다! 
- 설명을 드리면, 모임 `신청 수`가 아니라 `승인된 신청 수`를 반환해야 했습니다! 하지만 제가 착각을 해서 옛날에 `신청 수`로 구현했었습니다! 그래서 최근에 `신청 수`가 아닌 `승인된 신청 수`를 반환하도록 로직을 변경했습니다. 하지만 변수명은 아직 `appliedCount (신청 수)`로 되어있습니다. 이게 자꾸 헷갈리게 만든다고 생각해서 개선하고자 했습니다!
- 원래는 meeting/v2/patch-1 이런식으로 새로운 API를 만들려고 했는데요!
- 그런 방식은 필드 하나 바꾸는 거에 비해 너무 수정 범위가 크다고 생각했습니다!
- 간단하게 해결할 방법 고민하다가 그냥 필드를 추가한 후에, 나중에 마이그레이션 끝나면 해당 필드 삭제 하는게 가장 효율적일 것 같아 그렇게 구현했습니다!
- QueryProjection 를 사용하지 않는데 남아있더라고요! 그래서 이 부분 삭제했습니다.
- 모임 제목 에만 private final 이 안되어 있더라고요?! 단순 실수인 것 같아 수정했습니다!
- closed #432
> refactor: 승인된 신청자 수 필드 추가

- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
- approvedCount 필드 추가했습니다.
- closed #465
> chore: approvedCount 필드 추가

- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeader.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- 모임장은 공동모임장이 될 수 없도록 구현했습니다.
- closed #475
> fix: 모임장은 공동모임장이 될 수 없다.

- main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/EnMeetingStatus.java
- main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationEnums.java
- main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
- main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationService.java
- main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationRequestDto.java
- main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockService.java
- main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
- main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/global/pagination/dto/PageOptionsDto.java
- main/src/main/java/org/sopt/makers/crew/main/global/util/AdvertisementCustomPageable.java
- main/src/main/java/org/sopt/makers/crew/main/global/util/CustomPageable.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingApi.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingController.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllMeetingDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllMeetingQueryDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/UserOrgIdRequestDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
- main/src/test/java/org/sopt/makers/crew/main/entity/meeting/MeetingTest.java
- APP BE 와의 통신을 위한 모임 목록 조회 API 개발 했습니다.
- 아직 모임 목록 조회 정책이 확실히 정해지지 않았지만 APP 쪽에서 딜레이가 계속 생길 것 같아 먼저 구현했습니다.
- 저희가 외부 서비스를 사용하는 경우 `external`, 외부 서비스가 저희 서비스를 사용하는 경우 `internal` 이라고 정의하고자 했습니다. 의견 궁금합니다! 
- 기존에는 플그 토큰 받아서 진행하고자 했습니다. 하지만 플그와의 소통을 줄이고 싶어 화이트 리스트에 등록해서 구현했습니다. 의견 궁금합니다! 현재는 단순히 플그 id만 받아서 구현한 상황입니다.
- closed #484
> feat: APP BE 와의 통신을 위한 모임 목록 조회 API 개발

- main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingResponseDto.java
- app 쪽 요청에 따라 `category` 필드를 추가했습니다.
- closed #490
> chore: category 필드 추가

- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/ApprovedStudyCountProjection.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/ApprovedStudyCountResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
- app be를 위해 스터디 수 조회 API를 구현했습니다.
- 솝커톤 조회 API의 경우 아직 앱쪽에서 기획 확정이 되지 않아서 보류하고 작업했습니다.
- 앱 측에서 스터디 수 조회 API만 필요하다는 의견이 다시 나와, 스터디 수 조회 API만 구현하기로 결정하였습니다.
- closed #488
> feat: app be를 위한 스터디 수 조회 API 구현

- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- userActivity 가 null 인 경우 NPE 가 발생하여 500에러가 발생하고 있습니다.
- closed #495
> fix: 검증 로직 일부 수정

- main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
- prometheus actuator 경로를 화이트리스트에 추가했습니다.
- 하나의 모니터링 서버에서 dev, prod 서버의 스프링 컨테이너 metric을 수집하기 위해서는 토큰 없이 접근할 수 있도록 해야하기에 화이트리스트에 추가하게 되었습니다.
- closed #510
> refactor: prometheus actuator 경로 화이트리스트에 추가 완료

- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetRecommendDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- 추천 모임 목록 조회하는 기능을 구현했습니다.
- 기능 명세서에 default 는 '현재 모집중인 모임'을 반환해야해서 querydsl 동적쿼리를 사용했습니다.
- closed #521
> feat: 추천 모임 목록 조회 구현

- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningPlaceType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagType.java
- 번쩍 관련 객체를 정의했습니다. 아래 내용보시면서 봐주시면 좋을 것 같습니다! 이외에도 변수명, 타입 등등 여러 피드백 환영입니다!
- https://www.notion.so/sopt-makers/11de266d58294416a221d38b5a614310?pvs=4
- closed #507
> feat: 번쩍 관련 객체 정의

- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/converter/LightningPlaceTypeConverter.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/converter/LightningTimingTypeConverter.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningPlaceType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningTimingType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/TagType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeMessageType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeTypeConverter.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyWithoutWelcomeMessageDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2CreateLightningResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateTagResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
- main/src/main/resources/application-dev.yml
https://www.notion.so/sopt-makers/cb7a4bf4670940f399d7fa45c6667e92?pvs=4
- 번쩍 개설 기능을 구현하였습니다.
- 명세서는 위에 적어두었습니다.
- 번쩍 개설 시, 환영태그를 받게 되는데, 이를 Tag 엔티티에서 관리하게 됨으로서 DTO 관련해서 고민이 좀 있었습니다.
- 일단은 코드 상 1번 로직이 가져다주는 장점이 많기때문에 1번으로 진행했으나, 클라이언트측의 의견을 들어보고 바꿔야 될 수도 있을 것 같습니다!
- **LightningV2CreateLightningBodyDto와 같이 봐주시면 될것 같습니다.**
- 해당 DTO를 만들게 되면, 중복 코드도 사라지고, 번쩍 개설 요청 객체 필드만 꺼내서 toLightningEntity로 보낼 수 있기 때문에 코드가 깔끔하다는 장점이 있습니다.
- 단, 클라이언트 측에서 요청 구조를 바꿔야 하기 때문에 공수가 더 들 수도 있을 것 같다는 생각이 듭니다.
- 해당 DTO를 만들게 되면 중복 코드도 늘어나는 단점이 있습니다(번쩍 개설 요청 필드, 환영태그 필드를 모두 명시한 DTO를 다시 생성해야함) 
- 또한, 번쩍 개설 요청 객체 필드만 꺼내서 toLightningEntity로 보낼 수 없고, 번쩍 개설 요청 필드만 포함된 DTO 객체를 서비스 로직 중간에 만들어서 toLightningEntity로 보내야한다는 단점이 있습니다.
- targetDesc이 사용되지 않는 필드로 잡히고 있고, DB에 계속 Null로 정보가 들어가고 있는 상황인 것 같습니다.
- 또한, MeetingRedisDto에서도 …
> feat: 번쩍 개설 기능 구현

- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningTimingType.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyWithoutWelcomeMessageDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
- 번쩍 엔티티에 startDate, endDate 필드를 추가하였습니다.
- 기획 변경에 대해서 싱크 맞추는 작업을 하였습니다. (LightningTimingType에서 기간 삭제)
- 본래 번쩍 상세 조회 GET API를 작업하다가, 기획이 변경이 되어 FE 분들을 위해 중간 PR을 날리게 되었습니다.
- 따라서 번쩍 상세 조회는 새롭게 이슈를 파서 작업하겠습니다!
- closed #533
> feat: 번쩍 엔티티에 startDate, endDate 필드 추가 및 기획 변경 싱크 맞추기

- main/src/main/java/org/sopt/makers/crew/main/global/advice/ControllerExceptionAdvice.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/BaseException.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/ExceptionResponse.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyWithoutWelcomeMessageDto.java
- ExceptionHandler 예외 메시지를 구체화하였습니다.
- Valid 어노테이션과 관련해서 번쩍 관련 로직을 수정했습니다.
- 예외 메시지를 구체화 처리함으로서 클라이언트 측에서 예외 대응을 빠르게 할 수 있도록 하였습니다.
- closed #536
> refactor: ExceptionHandler 예외 메시지 구체화 및 번쩍 관련 로직 수정

- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
- main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSetting.java
- main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingConfig.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingForLightningResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/resources/application-dev.yml
- main/src/main/resources/application-local.yml
- main/src/main/resources/application-prod.yml
- main/src/main/resources/application-test.yml
현재 번쩍 모임 개발을 진행하면서, 기존 API를 유지하면서 새로운 기능을 통합할 수 있는 방법을 고민했습니다. 여러 방안을 검토한 결과, 최적의 솔루션으로 Lightning 테이블에 meetingId를 두고, MeetingCategory가 번쩍일 경우 해당 정보를 Lightning 테이블에 저장하는 방식을 선택했습니다.
1. Apply 테이블과 기존의 구조:
- Apply 테이블에서 meetingId가 외래키로 사용되기 때문에, 기존 구조를 대폭 변경하거나 새로운 번개 지원 API를 개발하는 것은 많은 리소스가 소요되며, 구조적으로 복잡해질 가능성이 큽니다.
2. 상속 테이블 전략 검토:
- SINGLE_TABLE 전략: Meeting과 Lightning 데이터를 같은 테이블에 저장하는 전략이지만, 필드에 null 값이 많아질 가능성이 높아 제외했습니다.
- JOINED 전략: 공통 필드는 Meeting 테이블에, 전용 필드는 Lightning 테이블에 저장하는 방식이지만, 공통 필드를 현재 정책과 로직에 맞게 재구성하는 데에 많은 부담과 위험이 따릅니다. 또한, 공통 필드를 둬도 정책적 차이로 인해 의미가 없다고 판단하여 제외했습니다.
이러한 이유로, Lightning 테이블에 meetingId를 두고, MeetingCategory가 번쩍일 경우 Lightning 테이블에 정보를 저장하는 방식이 최선이라고 판단했습니다. 이를 통해 새로운 API를 개발할 필요성을 최소화하고, 필요한 경우 번쩍 상세 조회와 번쩍 개설 정도의 API만 추가하면 될 것으로 예상됩니다.
- 기존 API 구조를 대부분 유지할 수 …
> refactor: 번쩍 모임 생성 시 모임 정보를 먼저 저장하도록 변경 완료

- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
- main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2CreateLightningResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2GetLightningByMeetingIdResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
- 번쩍 상세 조회 GET API를 구현했습니다.
- 처음에 번쩍 상세 조회를 설계했었을 때, 번쩍 id로 조회할 수 있도록 하려고 했습니다.
- 그런데 프론트 분들에게 물어본 결과 전체 모임 리스트 조회 시에도 모임 id를 사용하고 있다고 했었고, 번쩍 id를 프론트에서 새롭게 관리해야 한다는 부담감이 있을 것이라고 판단했습니다.
- 따라서 프론트 분들은 meetingId만 알고 있고, 이를 조회 시 보내면 번쩍 엔티티에도 meetingId를 저장하기 때문에 이를 이용해서 번쩍 정보들을 조회하는 방식으로 구현하였습니다.
- 따라서 저번에 번쩍 개설 시 주던 lightningId도 meetingId를 주도록 변경하였습니다.
```java
MeetingCreatorDto meetingLeader = userReader.getMeetingLeader(lightning.getLeaderUserId());
```
- 현재 LightningV2ServiceImpl에서도 모임장 정보를 조회하기 위해 해당 메서드를 사용하고 있습니다.
- 이번 번쩍 상세 조회에서도 레디스의 캐시를 사용하게 되었는데, 혹시 getMeetingLeader를 2개의 서비스 레이어에서 접근하는 것에는 문제가 없는지 여쭙고 싶습니다. (문제는 없을 것 같은데 혹시 몰라서 여쭈어봤습니다!)
- 스웨거로 테스트한 response 입니다.
- closed #539
> feat: 번쩍 상세 조회 GET API 구현 완료

- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/TopFastestAppliedMeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/TopFastestAppliedMeetingsResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
- 가장 빠르게 신청한 모임 N개 조회 API 개발했습니다.
- 3개로 고정하려다가 요청사항이 바뀔수도 있을것 같아 requestParam 으로 갯수를 받았습니다! 디폴트는 3으로 해뒀습니다!
- closed #559
> feat: 가장 빠르게 신청한 모임 N개 조회 API 개발

- main/.gitignore
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- 모집중, 모집전, 모집마감 순으로 모임조회 정렬 로직을 변경하였습니다.
- 같은 카테고리(모임 모집 상태)의 경우 기존처럼 id 순으로 최신순 정렬을 하도록 하였습니다.
- 첫번째 이미지는 page1의 응답값, 두번째 이미지는 page2의 응답값입니다.
- postman으로 확인했을 때, 모집중 -> 모집전 -> 모집마감 순으로 최신순 정렬을 하는것을 확인했습니다.
- 현재 AOP로 레포지토리 쿼리 응답속도를 측정해보니 거의 2배 차이가 납니다. 따라서 추후 최적화를 해야할 것 같습니다.
- 여러번 time.now()를 호출할경우 결과가 매번 다르게 평가될 가능성이 있어, 쿼리 실행 시 불일치한 결과가 발생할 수 있습니다.
- 따라서 동일한 now 값을 사용하게 하여 예상치 못한 미묘한 시간 차이 문제를 방지하도록 하였습니다.
- closed #485
> refactor: 모집중, 모집전, 모집마감 순으로 모임조회 정렬 정책 변경

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/global/constant/CrewConst.java
- main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/global/util/ActiveGenerationProvider.java
- main/src/main/java/org/sopt/makers/crew/main/global/util/DefaultActiveGenerationProvider.java
- main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/FlashMeetingMapper.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/global/util/TestActiveGenerationProvider.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- 최신 기수(36th) 변경에 따른 Crew Const의 ACTIVE_GENERATION을 변경했습니다.
- 지금 36기로 상수를 바꾸면서 `canJoinOnlyActiveGeneration` boolean 필드가 false로 나와 테스트 결과가 달라지는 상황입니다!
- `getMeetings`를 호출할 때, 비즈니스 로직 내에서 ACTIVE_GENERATION=36 과 비교를 하기 때문에 false가 나오고 있습니다.
- 테스트 코드에서 ACTIVE_GENERATION을 전역적으로 고정해서, 다음 기수가 진행되어도 영향이 없도록 설계를 해야할 것 같은데 좋은 방법 있으시면 의견주시면 감사하겠습니다!
```java
public interface ActiveGenerationProvider {
Integer getActiveGeneration();
}
```
```java
@Component
@Profile("!test")
public class DefaultActiveGenerationProvider implements ActiveGenerationProvider {
@Override
public Integer getActiveGeneration() {
return CrewConst.ACTIVE_GENERATION;
}
}
```
```java
@Component
@Profile("test")
public class TestActiveGenerationProvider implements ActiveGenerationProvider {
private static final Integer …
```
> refactor: 최신 기수(36th) 변경에 따른 Crew Const 변경

- main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyInfoDetailDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyWholeInfoDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingGetApplyListResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
- playground 에서 모임 신청하였을 때 순번이라는 개념을 추가하기 위한 정보를 제공하기 위해 api 응답을 수정하였습니다.
- 추가로 모임을 신청한 사람 순번대로 정보를 제공하기 위하여 정렬하여 응답하는 작업 진행하였습니다.
- 모집 현황 리스트
- 신청자 관리
- 참여자 리스트
- 현재 진행하면서 사실 이름 정하기가 제일 어려웠던 거 같습니다.
- 모임 참여자에 뜰 이 순번 관련하여서 applyNumber로 잡았는데 다른 변수명 추천받슴다...
- 추가로 list 를 조회하는 api 내부에서 사용하는 dto 의 경우 확인해봤을때 queryDsl과 강하게 결합되어있는 요소가 있어 변경에 있어 다른 객체로 분리를 하는 방향으로 진행하였는데요! 이런 친구들에 대해서 제가 생각한 방식대로 변경해보긴 했지만 동훈님이시라면 이런 상황에서 어떻게 대처하실 지 궁금하네요!
- closed #593
> feat: 모임 정보에 신청 순서 추가

- main/build.gradle
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingReader.java
- main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheInfo.java
- main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheQueryService.java
- main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CachesEndpointExtension.java
- main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CaffeineConfig.java
- main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisConfig.java
- main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingCacheDto.java
- main/src/main/resources/application-dev.yml
- main/src/test/java/org/sopt/makers/crew/main/external/CaffeineCacheConfig.java
- main/src/test/java/org/sopt/makers/crew/main/external/CaffeineTestConfig.java
- main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
redis -> local cache(caffiene) 으로 변환하는 과정을 수행해요!
이전에 회의 하였던것처럼 현재 진행하였습니다.
앞에 actuator path + 아래와 같은 path 들로 조회할 수 있습니다.
- cachecontents/caches -> cache key 종류 확인
- cachecontents/캐시명 -> 가지고 있는 id들 조회
- cachecontents/캐시명/id -> 해당 캐시 단건 조회
- closed #596
> refactor: redis -> 로컬 캐시로 변환

- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
- main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingCreatorDto.java
- main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
- 모임 삭제 시 관련된 모든 캐시 항목을 제거하도록 수정했습니다. (이슈에 이유가 정리되어 있습니다)
- 위 작업을 진행하며 조그마한 개선 작업도 진행했습니다.
https://until.blog/@octoping/record%EC%97%90%EC%84%9C-%EB%B0%B0%EC%97%B4-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EA%B8%B0
- DTO들을 보다가 `Override equals, hashCode and toString to consider array's content in the method`라는 경고가 `MeetingV2GetCreatedMeetingByUserResponseDto`가 뜨는 것을 보고 궁금해서 조사를 해보았습니다.
- 그 결과, 흥미로운 사실을 알게 되었는데요! 배열(Array)은 참조 타입이기 때문에 Objects.equals()를 사용하면 참조가 같을 때만 true를 반환합니다. 즉, 배열의 내용을 기준으로 비교하지 않기 때문에 record의 equals 연산은 우리가 기대하던 대로 동작하지 않게 됩니다.
- 따라서 equals, hashCode, toString 메서드를 직접 오버라이드하여 배열 타입의 동등성을 정확히 판단할 수 있도록 수정했습니다.
- List 인터페이스를 구현한 컬렉션(ArrayList, LinkedList 등)은 기본적으로 내용 기반으로 equals()와 hashCode()를 구현하기에 앞으로 Record에서는 배열 사용을 지양하는게 좋을 것 같다는 생각이 들었습니다 ㅎㅎ
- closed #555
> fix: 모임 삭제 시 관련된 모든 캐시 항목을 제거하도록 수정

- main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/event/FlashLeaderSyncEventDto.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/event/FlashLeaderSyncEventListener.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- 번쩍 상세 조회 시 userId update로직을 별도의 이벤트 클래로 분리를 진행하였습니다.
- 기존에 Transactional(readOnly = true)옵션에서 getFlashDetail 메서드가 호출되는데, private 메서드는 호출하는 상위 메서드의 트랜잭션 속성을 상속받기에 readOnly 속성을 그대로 가져오게 되는 문제가 있었습니다.
- 따라서 번쩍 상세 조회 시, userId 정합성 문제가 발생하면 이를 이벤트로 별도의 쓰레드에서 userId를 수정하도록 변경하였습니다.
- 처음에는 readOnly 특성으로 인해 userId update 로직을 새로운 서비스로 분리하고 이를 Transactional + public으로 열어두어 호출하도록 할 생각이었습니다.
- 하지만, 이는 결국 상세 조회 response 시간에 영향을 받게 되고, Transactional(readOnly = true)의 효과를 누리지 못한다고 판단했습니다.
- 비동기 이벤트 방식(이벤트 리스너 + AFTER_COMMIT + Async)을 사용함으로써 사용자 응답 시간에 영향을 주지 않으면서도 데이터 정합성을 유지할 수 있습니다.
- 또한, 이벤트 방식은 관심사 분리 원칙에도 부합합니다. 조회 로직은 조회에만 집중하고, 동기화 로직은 별도로 처리됩니다.
- closed #626
> fix: Flash 리더 정보 동기화 로직을 이벤트 기반 비동기 처리 방식으로 개선

- main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/MeetingKeywordType.java
- main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeMessageType.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateAndUpdateResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateAndUpdateFlashTagResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
- 번쩍 개설 및 수정 시 모임 키워드 등록 기능을 구현하였습니다.
- 현재 dev 전용 스키마에 `welcomeMessageTypes`를 jsonb 타입으로 추가한 상태입니다. (local 스키마가 없는 관계로...)
- 따라서, dev서버에서 번쩍 개설 및 수정 시 requestDTO의 meetingKeywordTypes이 null로 넘어와 작동하지 않는게 정책에는 맞지만 dev서버에서 작동하도록 하기위해 현재 null을 허용해둔 상황입니다!!
- closed #642
> feat: 번쩍 개설 및 수정 시 모임 키워드 등록 기능 구현 완료

- main/src/main/java/org/sopt/makers/crew/main/external/notification/event/NotificationTimeValidator.java
- main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
- main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/external/notification/event/NotificationTimeValidatorTest.java
- **시간대별 알림 제어**: 22시~08시 사이에만 키워드 매칭 알림 발송하도록 시간 제한 기능 추가
- **알림 시간 검증 로직**: `NotificationTimeValidator`를 통한 시간대별 알림 제어
- `NotificationTimeValidator.java`: 알림 시간대 검증 로직
- closed #675
- [] docker-compose.yml 파일에 마이그레이션 한 API의 포워딩을 변경해줬나요?
- [] Spring Secret 값을 수정하거나 추가했다면 Github Secret에서 수정을 해줬나요?
- [] Nestjs Secret 값을 수정하거나 추가했다면 Docker-Compose.yml 파일 및 인스턴스 내부의 .env 파일을 수정했나요?
> feat: 오후 10시 이후 오전 8시 이전엔 번쩍 생성 알림이 가지 않도록 진행해요!

- main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/projection/UserKeywordsProjection.java
- main/src/main/java/org/sopt/makers/crew/main/entity/user/projection/UserKeywrodsProjection.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/UpdateUserInterestKeywordRequestDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetInterestedKeywordsResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
- main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
- 유저 관심 키워드(관심있는 키워드) 저장 및 조회 기능 구현
- 관심 키워드 저장/수정 API 구현 (`UserV2ServiceImpl`, `UserV2Controller`, `UserRepository` 등)
- 관심 키워드 조회 API 구현 및 응답 DTO 추가
- 관련 Projection, Entity, Service, Controller, Test 코드 추가 및 수정
- 관심 키워드 관련 테스트 코드 작성
- 관심 키워드 저장/조회 기능이 정상적으로 동작하는지 통합 테스트를 통해 검증했습니다.
- Projection, Query, DTO 등에서 오타 및 네이밍을 한 번 더 점검하면 좋을 것 같습니다.
- 관심 키워드가 없는 경우도 정상적으로 빈 리스트로 반환됩니다.
- closed #682 
---
> fix: 유저 키워드 post 전송시 문제가 되었던 수정, get을 통한 키워드 조회 진행할 수 있도록 변경

- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
- 일반 모임 삭제 후 존재하지 않는 meetingId로 조회 시 404 에러를 반환하도록 변경을 완료했습니다.
- closed #685
> chore: 일반 모임 삭제 후 존재하지 않는 meetingId로 조회 시 404 에러를 반환하도록 변경 완료

- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
- main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingApi.java
- main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingController.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingForWritingPostDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllWritingPostResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
- Internal 용 모임 전체 조회(피드 작성용) API 추가  
- `InternalMeetingApi`, `InternalMeetingController`, `InternalMeetingService`에 모임 전체 조회 API 및 관련 메서드 구현
- 전체 조회용 DTO 추가  
- `InternalMeetingForWritingPostDto`, `InternalMeetingGetAllWritingPostResponseDto` 신규 생성
- 레포지토리 전체 조회 메서드 추가  
- `MeetingSearchRepository`, `MeetingSearchRepositoryImpl`에 `findAllByQuery(Pageable)` 메서드 및 관련 로직 구현
- 내부 피드 작성 시 모임 전체 조회가 필요한 요구사항을 반영했습니다.
- 페이징 처리 및 DTO 구조를 단순화하여 확장성을 고려했습니다.
- 네이밍 및 API 경로에 대한 피드백 환영합니다.
- closed #692
> feat : 플크루 협업 작업을 위한 api 중 get 메서드 작업 진행

- main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
- main/src/main/java/org/sopt/makers/crew/main/global/config/WebMvcConfig.java
- 보안 관련 설정을 SecurityConfig 한 곳에서 통합 관리 및 allowCredentials를 false로 변경했습니다.
- closed #719
> refactor: 보안 관련 설정을 SecurityConfig 한 곳에서 통합 관리 및 allowCredentials를 false로 변경

- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostViewCountResponseDto.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
- main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
- 기존에 있었던 조회 시 증가 로직을 분리하여 다른 api로써 증가시킬 수 있도록 구현
- closed #743
> feat: 게시글 조회수 증가용 api 구현 진행
